### ISSUE TITLE
[Bug]Coloured chat resets on new line

### ISSUE THREAD

**Issue by Biofusionz** [ForgeEssentials/ForgeEssentialsMain#1307] opened 2015-02-23 22:15 UTC
Title says it all, when chat goes to a new line, MOTD or normal chat, the colour reverts back to white.
http://ctrlv.in/507203/annotated

**Comment by Biofusionz** [comment] 2015-02-23 22:16
Title says it all, when chat goes to a new line, MOTD or normal chat, the colour reverts back to white.
http://ctrlv.in/507203/annotated

**Comment by olee** [comment] 2015-02-23 22:45
Ah yeah... I also noticed that quite a while ago, but no one bothered to fix it :smile: 
The problem is that minecraft in-text color-codes get reset on each line.
The only way to cover multi-line coloring is by generating kinda special messages.

**Comment by luacs1998** [comment] 2015-02-23 23:16
Dupe of #1209

**Closed by luacs1998** 2015-02-23 23:16 UTC

**Comment by olee** [comment] 2015-03-14 11:40
This one is a little bit different.
#1209 was about the error/success messages sent by FE.
This problem here however is a bug in minecraft itself that does not keep the color-codes for the next line of text.
We could do a workaround by parsing the text, filtering color-codes and reformatting all that into ChatCompontents.
However this would take a lot of work and I'd rather see Minecraft fix that one itself.
If you have problems with coloring in MOTD, just add additional color-codes at the points where the lines break and you will be OK.

**Comment by olee** [comment] 2015-03-14 14:18
This one will probably handled the same time we fix https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1342.
