### ISSUE TITLE
Hibernate loading issue

### ISSUE THREAD

**Issue by Paul17041993** [ForgeEssentials/ForgeEssentialsMain#1489] opened 2015-05-12 08:50 UTC
Bed re-spawning enabled, if the bed resides next to a wall and the player is killed, they can end up spawning inside the wall and suffocating.

Fix; check all sides and the top of the bed for adequate air before placing the player.

notes;
- affects /bed command.
- appears that the bed only ever places the player at the head-end of the bed, which tends to be the most likely facing a solid wall. Or the north-west corner, Haven't yet confirmed which it is.

**Comment by olee** [comment] 2015-05-12 10:05
This might actually be the fault of another mod.
I fixed the bed spawning some time ago and tested it throughly.
If the bed is surrounded with walls, it will tell the player that his bed is obstructed on respawn and he will spawn somewhere else.

**Comment by Paul17041993** [comment] 2015-05-12 11:48
the bed is not surrounded in walls, the re-spawn code fails to place the player in a safe location. Possibly a math error as it seems that the player is placed directly on one corner of the bed instead of in the center of a surrounding pair of air blocks. Are you adding the correct .5 values to the block coords?

**Comment by olee** [comment] 2015-05-12 14:42
So let me ask this first:
Did you actually update to latest version first?
I definitely fixed this bug.

**Comment by Paul17041993** [comment] 2015-05-12 21:39
'latest version' when? helps if you mention the numbers, server currently uses 1.4_beta6, which was the latest at 04/05/2015 (common d/m/y).

**Comment by evernife** [comment] 2015-05-13 00:10
Last version is: forgeessentials-1.7.10-1.4.0-beta7-server.jar
Try with this versions http://ci.forgeessentials.com/job/ForgeEssentials/

**Comment by Paul17041993** [comment] 2015-05-13 01:03
latest FE build (573) is defected;
[20:58:25] [Server thread/ERROR] [FML]: Caught exception from ForgeEssentials
javax.persistence.PersistenceException: java.lang.ClassNotFoundException: org.hibernate.ejb.HibernatePersistence
        at javax.persistence.spi.PersistenceProviderResolverHolder$PersistenceProviderResolverPerClassLoader$CachingPersistenceProviderResolver.loadResolverClasses(PersistenceProviderResolverHolder.java:160) ~[hibernate-jpa-2.1-api-1.0.0.Final.jar:1.0.0.Final]
        at javax.persistence.spi.PersistenceProviderResolverHolder$PersistenceProviderResolverPerClassLoader$CachingPersistenceProviderResolver.<init>(PersistenceProviderResolverHolder.java:122) ~[hibernate-jpa-2.1-api-1.0.0.Final.jar:1.0.0.Final]
        at javax.persistence.spi.PersistenceProviderResolverHolder$PersistenceProviderResolverPerClassLoader.getPersistenceProviders(PersistenceProviderResolverHolder.java:80) ~[hibernate-jpa-2.1-api-1.0.0.Final.jar:1.0.0.Final]
        at javax.persistence.Persistence.getProviders(Persistence.java:69) ~[hibernate-jpa-2.1-api-1.0.0.Final.jar:1.0.0.Final]
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:53) ~[hibernate-jpa-2.1-api-1.0.0.Final.jar:1.0.0.Final]
        at com.forgeessentials.playerlogger.PlayerLogger.loadDatabase(PlayerLogger.java:129) ~[PlayerLogger.class:?]
        at com.forgeessentials.playerlogger.ModulePlayerLogger.serverPreInit(ModulePlayerLogger.java:41) ~[ModulePlayerLogger.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_249_ModulePlayerLogger_serverPreInit_FEModuleServerPreInitEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
        at com.forgeessentials.core.ForgeEssentials.serverPreInit(ForgeEssentials.java:176) ~[ForgeEssentials.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
        at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:834) [Loader.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:273) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:256) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by evernife** [comment] 2015-05-13 01:12
Dude, paste the FULL LOG please.... (Here!! http://pastebin.com/ )

I am using the last version, pretty normal here...
Are you using FastCraft?

**Comment by Paul17041993** [comment] 2015-05-13 01:35
if you insist, I only posted what was necessary as the full log is thousands of lines long.
http://pastebin.com/0XN5aMx2

and no, I don't use fastcraft or anything closely related, I don't even support the use of optimisation mods in code already flooded with defects...

**Comment by evernife** [comment] 2015-05-13 01:40
You have AppleCore ? Sure?

Take a look here: #1449

**Comment by Paul17041993** [comment] 2015-05-13 02:01
that's even less helpful, means I'll be stuck with beta6 until #1449 is fixed, and fyi I see nothing in the changelogs about beds being changed.

Also, where's the jar build links for each individual build? there's only the links for the latest build on the job home page, so the only way for me to test specific builds is to build them myself, which I simply don't have that much spare time for...
Among the layout of the job pages in general looking severely broken, eg; the build list is supposed to be on the side, not the top, and this is definitely not something that should occur; http://prntscr.com/74lrj1

**Comment by olee** [comment] 2015-05-13 02:48
@Paul17041993 
That error looks like a different problem.
It seems the libraries needed for FE were not extracted correctly.
Try taking a look into `./ForgeEssentials/lib` directory and see if there are the following libraries:
````
antlr-2.7.7.jar
dom4j-1.6.1.jar
h2-1.3.175.jar
hibernate-commons-annotations-4.0.5.Final.jar
hibernate-core-4.3.7.Final.jar
hibernate-entitymanager-4.3.7.Final.jar
hibernate-jpa-2.1-api-1.0.0.Final.jar
jandex-1.1.0.Final.jar
javassist-3.18.1-GA.jar
jboss-logging-3.1.3.GA.jar
jboss-logging-annotations-1.2.0.Beta1.jar
jboss-transaction-api_1.2_spec-1.0.0.Final.jar
mysql-connector-java-5.1.22.jar
pircbotx-1.9.jar
xml-apis-1.0.b2.jar
````

**Comment by Paul17041993** [comment] 2015-05-13 04:34
all libs were there, even flushed them out and let it re-download, which was successful but still crashed.
cant attach a recent log as it seems the windows+java8 system emits 10k+ more lines than the cent6+java7 does, which is too much for pastebin...

**Comment by olee** [comment] 2015-05-13 06:46
Well the error tells me that JPA (Java Persistence API) was not able to load the Hibernate library for some reason.
Please at least provide a copy of the log from about 20 lines above the error and the rest after it (that should definitely fit into pastebin)

**Comment by Paul17041993** [comment] 2015-05-13 08:21
last fraction of the log on the win+java8 test server, haven't found anything else related to FE at the top of the log;
http://pastebin.com/sfnY789h
previous log before you mentioned of the libs was for cent6+j7, the libs file test was done only on the win+j8 as the cent6+j7 was reverted back to beta6 and left live until I can confirm of a FE update that's functional.

disabling applecore and hungeroverhawl allows the server to pass startup, but then breaks everything else in the process, forge is 10.13.3.1395-1710ls if not otherwise known.

**Comment by Paul17041993** [comment] 2015-05-13 08:29
ok now that I reminded myself of the forge version, build 1403 seems to have gotten somewhere, FE should have the minimum forge version set if it were the case of a dependency of a certain fix.

Will post back after the cent6+j7 has been tested.

**Comment by Paul17041993** [comment] 2015-05-13 08:53
Nope, again failed to start, only difference being java and OS;
http://pastebin.com/8EX21SB6
and yes, I made sure to purge the libraries.

**Comment by melekaiah** [comment] 2015-05-13 09:02
I cant fully test this at the moment, but this was way back in beta 5 of forge essentials for me. which is still happening because we cant update due to the mixin error stuff. 

It would help a lot with the testing if you a library of the older releases actually were available to test. most admins dont do compiling themselves to test something.

**Comment by olee** [comment] 2015-05-14 13:49
@Paul17041993 the libraries could not be extracted!
````
[com.forgeessentials.core.preloader.classloading.FEClassLoader:extractLibs:43]: [ForgeEssentials] Could not find library folder - will create new one and re-extract libraries.
[com.forgeessentials.core.preloader.classloading.FEClassLoader:runClassLoad:70]: [ForgeEssentials] Something happened that shouldn't have happened. Trying to recover.
[com.forgeessentials.core.preloader.classloading.FEClassLoader:runClassLoad:110]: [ForgeEssentials] Loaded 0 modules
[com.forgeessentials.core.preloader.classloading.FEClassLoader:checkLibs:150]: [ForgeEssentials] You are missing the following library files.
....
````

Maybe FE does not have write-access to the ForgeEssentials folder?
Try extracting the libraries manually.
To do that open the server-jar with a ZIP tool and extract the libraries.zip that is contained in it.
Extract this one to your server installation.

**Comment by Paul17041993** [comment] 2015-05-14 23:55
if a lib extraction failure is the case, then the recent beta7 releases are incompatible with linux, because beta7 works fine on windows and beta 6 works fine on linux excluding the bugs.

You'll have to check back through what was changed with the lib system between b6 and the latest releases, or check the filenames of the libraries are being parsed correctly, don't forget about case-sensitivity...

**Comment by olee** [comment] 2015-05-16 23:22
Sorry but I got a bit confused here right now and don't really know what's the current state any more.
Can you please get the latest version of FE again and try starting a clean server instance?
In case of failure, please send the log. You can use https://gist.github.com/ to past large logs.

**Comment by Paul17041993** [comment] 2015-05-17 06:19
now nolonger loads on win+j8, as such I cant test it on the linux box unless it passes a basic load on win first.
http://pastebin.com/NYXhcrrX

**Comment by olee** [comment] 2015-05-17 12:01
Ok there must be something really wrong with your system setup or something else.
I am using Win+Java8 myself and I know that FE loads without a problem.
Did you try starting a server without any other mods beside FE?

**Comment by olee** [comment] 2015-05-17 12:04
@luacs1998 I need your help on this one.
Currently it seems only to affect @Paul17041993 alone, but we should make sure it's not FE's fault.

**Comment by luacs1998** [comment] 2015-05-17 12:38
Probably not today or tomorrow - I need to setup a Linux VM...

**Comment by Paul17041993** [comment] 2015-05-17 21:42
latest b7 FE (587) passes start with hunderoverhawl and applecore disabled, however the previous b7 build I tested (573) would work correctly with them enabled.

so applecore compatibility was fixed, then broken again after 573...

**Comment by luacs1998** [comment] 2015-05-18 02:13
Logs?

**Comment by liach** [comment] 2015-05-18 02:21
So 580 is normal but 581 is not?

**Comment by Paul17041993** [comment] 2015-05-18 04:17
full logs for the latest build, had to use onedrive;
applecore and hungeroverhawled enabled, with crash;
http://1drv.ms/1LcEhvb
disabled and successful start;
http://1drv.ms/1LcEjmI

**Comment by helinus** [comment] 2015-05-18 19:11
Just FE build 588 on forge 1277 and java7 throws the same hibernate error, with playerlogger disabled it starts fine though.
https://gist.github.com/helinus/27a69a7dd293cc9d853e

**Comment by olee** [comment] 2015-05-18 23:19
Ok this is serious. 
It works perfectly on my server using forge 1388.
I wonder what happened there....

**Comment by luacs1998** [comment] 2015-05-19 00:43
Alright, update on my end:

My main computer crashed last Sunday, and the earliest I can get it back up is probably next weekend (reinstalling 60gb of programs is NOT FUN).

So I'll be working on recovering my main PC first. I have a spare PC, but that's not connected to the Internet so even if I do come up with a fix, I may not be able to commit any fixes I make.

From preliminary investigation of the logs, it seems to be that there's some sort of error being thrown when the library loader attempts to create the FE folder. This could be potentially related to the move to a FMLConstructionEvent for library loading.

I'll try to make some hacks around that by using the mixin config load-time hook to load libraries, but it may not work.

@olee for reference, the new FEClassLoader().extractLibs call in ForgeEssentials.java is the potential point of failure.

**Comment by olee** [comment] 2015-05-19 01:10
Well it's just interesting that FE loads on my own server with forge 1388 without a problem.
I will try out some things and see if I can replicate this issue.

**Comment by luacs1998** [comment] 2015-05-19 01:22
Sure, I still have a working phone with IRC, pm me if you need help.

**Comment by Paul17041993** [comment] 2015-05-19 01:51
various things could have changed between forge 1388 and 1403. And @olee what platform and java version does yours use? as well as applecore, etc versions.

**Comment by liach** [comment] 2015-05-19 02:05
Just a loading screen as far as I know. And merged Forge Mod Loader in 1406. luacs's pr was applied in 1399, reverted in 1400.

**Comment by DPxKnightxZero** [comment] 2015-05-21 23:48
Use 1408 Forge it has a ton of otherwise painful and previously persistent bugs.

**Comment by Paul17041993** [comment] 2015-05-22 07:29
tp to bed and home (set is fine) (this issue originally) and help permissions (#1481) are still broken in the latest build, other commands are fine.

**Comment by luacs1998** [comment] 2015-05-23 01:04
Neither me nor @olee can reproduce this issue.

Can you try extracting libraries.zip from within the FE jar manually?

**Closed** 2015-05-23 04:09 UTC
Labels: bug, highpriority
