### ISSUE TITLE
[Bug] Console Saving permissions... spam

### ISSUE THREAD

**Issue by Biofusionz** [ForgeEssentials/ForgeEssentialsMain#1364] opened 2015-03-24 14:41 UTC
I have a mob farm set up using OpenBlocks spikes to kill the mobs, occasionally it spams console when the mob is being killed with: [permission persistence/INFO] [ForgeEssentials]: Saving permissions...

![image](https://cloud.githubusercontent.com/assets/6354132/6804103/b462d798-d233-11e4-8d16-b66469f6573a.png)

**Comment by luacs1998** [comment] 2015-03-24 22:42
Fake player problem, dupe of #1352

**Closed by luacs1998** 2015-03-24 22:42 UTC

**Comment by olee** [comment] 2015-03-29 06:13
Oh this might have given me a hint on #1352.
Maybe it's because the fake-players used there are random and are registered as new each time (causing the addition of a permission and therefor a save).
