### ISSUE TITLE
Latest version crashes with AppleCore

### ISSUE THREAD

**Issue by chrisk123999** [ForgeEssentials/ForgeEssentialsMain#1405] opened 2015-04-13 23:14 UTC
Launching my server with ForgeEssentials beta 7 with AppleCore results in the following crash.  Doesn't happen with ForgeEssentials beta 5.

```
[19:05:10] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:05:10] [main/INFO] [LaunchWrapper]: Loading tweak class name com.forgeessentials.core.preloader.FELaunchHandler
[19:05:10] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[19:05:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:05:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:05:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:05:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[19:05:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:05:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:05:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:05:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.reflect.Method.invoke(Method.java:483)
[19:05:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[19:05:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[19:05:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    squeek/applecore/asm/module/ModuleFoodStats.patchEntityPlayerInit(Lorg/objectweb/asm/tree/MethodNode;Z)V @91: invokevirtual
  Reason:
    Type 'org/objectweb/asm/tree/VarInsnNode' (current frame, stack[2]) is not assignable to 'org/objectweb/asm/tree/AbstractInsnNode'
  Current Frame:
    bci: @91
    flags: { }
    locals: { 'squeek/applecore/asm/module/ModuleFoodStats', 'org/objectweb/asm/tree/MethodNode', integer, 'org/objectweb/asm/tree/AbstractInsnNode' }
    stack: { 'org/objectweb/asm/tree/InsnList', 'org/objectweb/asm/tree/AbstractInsnNode', 'org/objectweb/asm/tree/VarInsnNode' }
  Bytecode:
    0000000: 2bb4 0094 bb00 9659 1100 bb1c 9900 0812
    0000010: 98a7 0005 129c b700 9fb8 00a3 4e2d c700
    0000020: 0dbb 004e 5912 a5b7 0053 bf2d b600 ab4e
    0000030: 2dc6 000d 2db6 00af 1100 b7a0 fff0 2dc7
    0000040: 000d bb00 4e59 12b1 b700 53bf 2bb4 0094
    0000050: 2dbb 00b3 5910 1903 b700 b6b6 00ba 2dc0
    0000060: 00bc 1c99 0008 1278 a700 0512 7ab5 00bf
    0000070: b1
  Stackmap Table:
    full_frame(@20,{Object[#2],Object[#76],Integer},{Object[#154],Uninitialized[#4],Uninitialized[#4],Integer})
    full_frame(@22,{Object[#2],Object[#76],Integer},{Object[#154],Uninitialized[#4],Uninitialized[#4],Integer,Object[#39]})
    append_frame(@43,Object[#167])
    same_frame(@62)
    same_frame(@76)
    same_locals_1_stack_item_frame(@107,Object[#188])
    full_frame(@109,{Object[#2],Object[#76],Integer,Object[#167]},{Object[#188],Object[#39]})
>
[19:05:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at squeek.applecore.asm.TransformerModuleHandler.<clinit>(TransformerModuleHandler.java:13)
[19:05:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:05:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[19:05:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:05:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
[19:05:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.newInstance(Class.java:433)
[19:05:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[19:05:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:101)
[19:05:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[19:05:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:05:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 6 more
```

**Comment by luacs1998** [comment] 2015-04-14 01:58
Do you have fastcraft installed? Consider looking into #1372

**Comment by chrisk123999** [comment] 2015-04-14 04:44
I do, however the issue doesn't happen when I downgrade ForgeEssentials.

**Comment by olee** [comment] 2015-04-14 09:22
So did you try running the server without FastCraft, but with AppleCore?
The difference from beta5 to beta6 is that we moved on to use Mixin for ASM patching which will probably become the standard for ASM in minecraft anyway.

**Comment by luacs1998** [comment] 2015-04-16 13:03
Dupe of #1372 - it's a problem between us and FastCraft, I'm dealing with it with Player now.

**Closed by luacs1998** 2015-04-16 13:03 UTC
