### ISSUE TITLE
Typing percent-sign '%', dollar '$' or backslash '\' in game chat disconnects the client

### ISSUE THREAD

**Issue by Fogger** [ForgeEssentials/ForgeEssentialsMain#1242] opened 2015-01-06 18:15 UTC
Reproduced in build #361 on Forge 1277 with only FE loaded.

With %  ->  http://hastebin.com/irulahabex.rb
With \ or $  ->  http://haste.pagefortress.com/silapovoge.avrasm

**Comment by Flukethoughts** [comment] 2015-01-06 18:32
!@#$%^&*()
More then one key does it.
just don't remember them all.

**Comment by Fogger** [comment] 2015-01-06 19:00
@Flukethoughts with the exception of the 2 keys we share, all of those you posted are ok.

New error with the string "% $ \ faaaaaaaaaaaaack"  ->  http://haste.pagefortress.com/etudupojew.avrasm

And another one  ->  http://haste.pagefortress.com/emoqunohun.rb

**Comment by luacs1998** [comment] 2015-01-08 03:05
Minecraft bug, just that something we do in the chat formatter exposes it. Mojang, you and your dirty workarounds...

I've seriously run out of ideas, so if anyone else wants to have their coders look into it and send me a PR to work around Mojang's code, feel free.

**Comment by olee** [comment] 2015-01-11 18:41
@luacs1998 I'm 99% sure it's not a minecraft bug. It's the _OutputHandler_ which does not handle these messages correctly. I wanted to fix that when cleaning up and improving chat-module, but I didn't get to it once I got busy again.

**Comment by luacs1998** [comment] 2015-01-11 22:33
Make a clean FG workspace, write your own mod that adds a test prefix and test chat formatting just like FE does, and tell me if you can't recreate this issue.

I did not come up with this conclusion blindly - O have spoken to quite a few people on IRC, and this is my conclusion.

**Comment by olee** [comment] 2015-01-11 22:34
I have a fix in mind and I will try it later (maybe ... if I have time ...)

**Comment by olee** [comment] 2015-01-11 23:49
@luacs1998 That's what I got just from debugging the FE ChatHandler - first the message-component before our chat-handler run, and after:
````
TranslatableComponent{
	key='chat.type.text',
	args=[
		TextComponent{
			text='ForgeDevName', 
			siblings=[], 
			style=Style{
				hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/msg ForgeDevName '}, hoverEvent=null}
		}, abc % abc
	], 
	siblings=[], 
	style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}
}

TranslatableComponent{
	key='[OPERATOR]<ForgeDevName> §rabc % abc', 
	args=[], 
	siblings=[], 
	style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
´´´´
Having the % and similar characters in the key-field seems to be the problem, but formatting it like above message should work.

**Comment by SinZ163** [comment] 2015-01-12 01:11
I dont have a workspace to test this, but I'm pretty sure the cause of $ and \ being weird (and crashing clients) is due to [FunctionHelper.replaceAllIgnoreCase](https://github.com/ForgeEssentials/ForgeEssentialsMain/blob/develop/src/main/java/com/forgeessentials/util/FunctionHelper.java#L450).

The problem lies in  `str.replaceAll(regex, replacement)`, as it's equivilant to:  `Pattern.compile(regex).matcher(str).replaceAll(repl)`
and `Matcher.replaceAll(repl)` treats $ and \ specially, and is suggested in javadocs to use `Matcher.quoteReplacement(repl)`

A viable solution (not tested) is: 
```java
return Pattern.compile("(?i)" + Pattern.quote(search)).matcher(text).quoteReplacement(replacement);
```

**Comment by olee** [comment] 2015-01-12 01:12
Ehm... it's already been fixed if you didn't notice yet...

**Comment by SinZ163** [comment] 2015-01-12 01:12
That fix only applied to %, $ can still crash clients

**Comment by luacs1998** [comment] 2015-01-12 01:26
@SinZ163 I'll apply your fix and see how it works out.

**Comment by Fogger** [comment] 2015-01-12 03:05
It no longer crashes, but Player names have dissapeared, so you can't tell who is speaking.

also, when typing $ or \, they are shown in chat with their escape chars, so \ becomes \\ and $ becomes \$.

**Comment by micmou** [comment] 2015-01-12 04:48
I can also confirm that it is fixed although player names are missing and the forward slash operator is shown

**Comment by luacs1998** [comment] 2015-01-14 02:15
Seeing as olee's fix was unable to fix the issue regarding $ and \, I will leave this issue open, and keep it at the "won't fix" status. If anyone has a coder willing to look into the issue and send me a PR fixing this, he is more than welcome to do so.

**Comment by olee** [comment] 2015-01-14 14:31
That's no reason to make it a "wontfix" issue. I will take a look at it.

**Comment by RlonRyan** [comment] 2015-01-15 18:55
It's because you are using bad regexes.

**Comment by RlonRyan** [comment] 2015-01-15 19:00
Are the regexes all that necessary? Why not just use string.replace?

**Comment by RlonRyan** [comment] 2015-01-16 00:27
Got it.

**Comment by RlonRyan** [comment] 2015-01-16 01:12
The real question is how this went unnoticed for so long...

**Closed** 2015-01-16 01:41 UTC
Labels: bug
