### ISSUE TITLE
portal frame shows glass blocks instead of portal animation

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentialsMain#1667] opened 2015-07-31 18:55 UTC
hey guys :)

Our portals are filled with vanilla glass blocks instead of portal animation blocks. I have tested to remove portal and renew but still glass blocks appear.

i am using version : forgeessentials-1.7.10-1.4.1.830-server.jar

is this a known bug ?

thanks in advance
-jogi

**Comment by luacs1998** [comment] 2015-08-01 01:09
Typical nether portals or ones created with /portal?

**Comment by luacs1998** [comment] 2015-08-01 02:42
Duplicate of #1649

**Closed** 2015-08-01 02:45 UTC
