### ISSUE TITLE
beta-6 - loading problem

### ISSUE THREAD

**Issue by NitroxydeX** [ForgeEssentials/ForgeEssentialsMain#1485] opened 2015-05-07 21:28 UTC
Server-Start fails right at the beginning with the following:

```
[23:21:53] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[23:21:53] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:21:53] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:21:53] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:21:53] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[23:21:53] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[23:21:53] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[23:21:53] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    cpw/mods/fml/common/asm/transformers/EventSubscriptionTransformer.buildEvents(Lorg/objectweb/asm/tree/ClassNode;)Z @387: invokevirtual
  Reason:
    Type 'org/objectweb/asm/tree/InsnNode' (current frame, stack[1]) is not assignable to 'org/objectweb/asm/tree/AbstractInsnNode'
  Current Frame:
    bci: @387
    flags: { }
    locals: { 'cpw/mods/fml/common/asm/transformers/EventSubscriptionTransformer', 'org/objectweb/asm/tree/ClassNode', 'java/lang/Class', 'org/objectweb/asm/Type', integer, integer, integer, integer, integer, integer, 'java/lang/String', 'java/lang/String', 'java/lang/String', 'java/lang/String', 'java/util/Iterator', 'org/objectweb/asm/tree/AnnotationNode', 'org/objectweb/asm/tree/MethodNode' }
    stack: { 'org/objectweb/asm/tree/InsnList', 'org/objectweb/asm/tree/InsnNode' }
  Bytecode:
    0x0000000: 2ab6 0057 b600 5d2b b400 6010 2f10 2eb6
    0x0000010: 0064 b600 6a4d 126c 2cb6 0070 9a00 0503
    0x0000020: ac12 72b8 0078 4e03 3604 0336 0503 3606
    0x0000030: 0336 0703 3608 0336 09b2 007c 03bd 0074
    0x0000040: b800 803a 0ab2 0083 03bd 0074 b800 803a
    0x0000050: 0b2d b600 873a 0c2d 03bd 0074 b800 803a
    0x0000060: 0d2b b400 8bb9 0091 0100 3a0e 190e b900
    0x0000070: 9701 0099 00b9 190e b900 9b01 00c0 009d
    0x0000080: 3a0f 190f b400 9f12 a1b6 001b 9900 1e19
    0x0000090: 0fb4 00a4 190a b600 1b99 0011 190f b400
    0x00000a0: a807 7e07 a000 0604 3605 190f b400 a804
    0x00000b0: 7e04 a000 5a19 0fb4 009f 12aa b600 1b99
    0x00000c0: 0013 190f b400 a419 0db6 001b 9900 0604
    0x00000d0: 3606 190f b400 9f12 acb6 001b 9900 1319
    0x00000e0: 0fb4 00a4 190b b600 1b99 0006 0436 0819
    0x00000f0: 0fb4 009f 12ae b600 1b99 0013 190f b400
    0x0000100: a419 0bb6 001b 9900 0604 3609 190f b400
    0x0000110: 9f12 afb6 001b 9900 1319 0fb4 00a4 190a
    0x0000120: b600 1b99 0006 0436 07a7 ff43 2bb4 00b2
    0x0000130: c600 d02b b400 b2b9 0091 0100 3a0e 190e
    0x0000140: b900 9701 0099 00bb 190e b900 9b01 00c0
    0x0000150: 00b4 3a0f 1509 9a00 5419 0fb4 00b5 12b7
    0x0000160: b600 1b99 0047 bb00 9d59 0412 ae19 0b01
    0x0000170: 01b7 00ba 3a10 1910 b400 bebb 00c0 5907
    0x0000180: b700 c1b6 00c7 1910 b400 bebb 00c0 5911
    0x0000190: 00ac b700 c1b6 00c7 2bb4 008b 1910 b900
    0x00001a0: c902 0057 0436 04a7 0056 1508 9a00 5119
    0x00001b0: 0fb4 00b5 12cb b600 1b99 0044 bb00 9d59
    0x00001c0: 0412 ac19 0b01 01b7 00ba 3a10 1910 b400
    0x00001d0: bebb 00c0 5907 b700 c1b6 00c7 1910 b400
    0x00001e0: bebb 00c0 5911 00ac b700 c1b6 00c7 2bb4
    0x00001f0: 008b 1910 b900 c902 0057 0436 04a7 ff41
    0x0000200: 1505 9900 2915 069a 0021 bb00 cd59 bb00
    0x0000210: cf59 b700 d012 d2b6 00d6 2bb4 00d7 b600
    0x0000220: d6b6 00da b700 ddbf 1504 ac2b b400 60b8
    0x0000230: 0078 3a0e 2bb4 00e0 bb00 e259 100a 12e4
    0x0000240: 190c 0101 b700 e7b9 00c9 0200 5715 079a
    0x0000250: 005f bb00 9d59 0412 af19 0a01 01b7 00ba
    0x0000260: 3a0f 190f b400 bebb 00e9 5910 1903 b700
    0x0000270: ecb6 00c7 190f b400 bebb 00ee 5911 00b7
    0x0000280: 190e b600 f112 af19 0a03 b700 f4b6 00c7
    0x0000290: 190f b400 bebb 00c0 5911 00b1 b700 c1b6
    0x00002a0: 00c7 2bb4 008b 190f b900 c902 0057 bb00
    0x00002b0: 9d59 0712 a119 0a01 01b7 00ba 3a0f 190f
    0x00002c0: b400 bebb 00e9 5910 1903 b700 ecb6 00c7
    0x00002d0: 190f b400 bebb 00ee 5911 00b7 190e b600
    0x00002e0: f112 a119 0a03 b700 f4b6 00c7 190f b400
    0x00002f0: bebb 00f6 5911 00b2 2bb4 00d7 12e4 190c
    0x0000300: b700 f9b6 00c7 bb00 fb59 b700 fc3a 1019
    0x0000310: 0fb4 00be bb00 fe59 1100 c619 10b7 0101
    0x0000320: b600 c719 0fb4 00be bb00 c059 1100 b1b7
    0x0000330: 00c1 b600 c719 0fb4 00be 1910 b600 c719
    0x0000340: 0fb4 00be bb01 0359 0603 0103 01b7 0106
    0x0000350: b600 c719 0fb4 00be bb01 0859 1100 bb2d
    0x0000360: b600 f1b7 010b b600 c719 0fb4 00be bb00
    0x0000370: c059 1059 b700 c1b6 00c7 190f b400 bebb
    0x0000380: 00e9 5910 1903 b700 ecb6 00c7 190f b400
    0x0000390: bebb 00ee 5911 00b7 190e b600 f112 aa19
    0x00003a0: 0d03 b700 f4b6 00c7 190f b400 bebb 00ee
    0x00003b0: 5911 00b7 2db6 00f1 12af b200 7c04 bd00
    0x00003c0: 7459 032d 53b8 0080 03b7 00f4 b600 c719
    0x00003d0: 0fb4 00be bb00 f659 1100 b32b b400 d712
    0x00003e0: e419 0cb7 00f9 b600 c719 0fb4 00be bb00
    0x00003f0: c059 1100 b1b7 00c1 b600 c72b b400 8b19
    0x0000400: 0fb9 00c9 0200 57bb 009d 5904 12aa 190d
    0x0000410: 0101 b700 ba3a 0f19 0fb4 00be bb00 f659
    0x0000420: 1100 b22b b400 d712 e419 0cb7 00f9 b600
    0x0000430: c719 0fb4 00be bb00 c059 1100 b0b7 00c1
    0x0000440: b600 c72b b400 8b19 0fb9 00c9 0200 5704
    0x0000450: ac                                     
  Stackmap Table:
    append_frame(@33,Object[#89])
    full_frame(@108,{Object[#2],Object[#44],Object[#89],Object[#116],Integer,Integer,Integer,Integer,Integer,Integer,Object[#23],Object[#23],Object[#23],Object[#23],Object[#147]},{})
    append_frame(@170,Object[#157])
    same_frame(@210)
    same_frame(@239)
    same_frame(@268)
    chop_frame(@297,1)
    chop_frame(@300,1)
    append_frame(@318,Object[#147])
    append_frame(@426,Object[#180])
    chop_frame(@509,1)
    chop_frame(@512,1)
    same_frame(@552)
    same_frame(@555)
    append_frame(@686,Object[#116])

[23:21:53] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.getDeclaredConstructors0(Native Method)
[23:21:53] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
[23:21:53] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.getConstructor0(Class.java:3075)
[23:21:53] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.newInstance(Class.java:412)
[23:21:53] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[23:21:53] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:101)
[23:21:53] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[23:21:53] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:21:53] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 6 more
```

Running Forge 1403 with 106 Mods.

**Comment by evernife** [comment] 2015-05-07 21:55
remove fastcraft.

**Comment by luacs1998** [comment] 2015-05-07 23:03
Dupe of #1449, and as evernife said, remove fastcraft.

**Closed by luacs1998** 2015-05-07 23:03 UTC
