### ISSUE TITLE
Error on player movement

### ISSUE THREAD

**Issue by mercsniper** [ForgeEssentials/ForgeEssentialsMain#1273] opened 2015-02-01 04:40 UTC
````
11:40:01 PM CONSOLE: thread/INFO] [JourneyMapServer]: On Request: Sending WorldID packet to: mercsniper
11:40:02 PM CONSOLE: persistence timer/INFO] [ForgeEssentials]: Saving permissions...
11:40:25 PM CONSOLE: thread/ERROR] [FML]: Exception caught during firing event com.forgeessentials.util.events.PlayerMoveEvent@10a0924e:
11:40:25 PM CONSOLE: thread/ERROR] [FML]: Index: 1 Listeners:
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 0: NORMAL
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 1: ASM: com.forgeessentials.worldborder.ModuleWorldBorder@5f66c9a1 playerMove(Lcom/forgeessentials/util/events/PlayerMoveEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 2: ASM: com.forgeessentials.teleport.portal.PortalManager@184509a0 playerMove(Lcom/forgeessentials/util/events/PlayerMoveEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 3: ASM: com.forgeessentials.permissions.core.PermissionEventHandler@5ebad654 playerMoveEvent(Lcom/forgeessentials/util/events/PlayerMoveEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$PlayerTickEvent@1de54769:
11:40:25 PM CONSOLE: thread/ERROR] [FML]: Index: 19 Listeners:
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 0: NORMAL
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 1: ASM: cofh.mod.updater.UpdateManager@cfb8ae0 tickStart(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 2: ASM: crazypants.enderio.item.MagnetController@11fb599d onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 3: ASM: crazypants.enderio.item.darksteel.DarkSteelController@18038a7b onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 4: ASM: com.rwtema.extrautils.crafting.LawSwordCraftHandler@2f7bbe09 event(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 5: ASM: com.forgeessentials.commands.util.CommandsEventHandler@48d41405 tickStart(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 6: ASM: mods.railcraft.common.blocks.hidden.TrailTicker@67580ce4 tick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 7: ASM: mods.railcraft.common.plugins.forestry.IceManTickHandler@20304213 tick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 8: ASM: mods.railcraft.common.items.firestone.FirestoneTickHandler@2ab6e3de tick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 9: ASM: tconstruct.armor.ArmorAbilities@698a8b2c playerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 10: ASM: pneumaticCraft.common.CommonHUDHandler@54b8f72b tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 11: ASM: cofh.mod.updater.UpdateManager@7686baf7 tickStart(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 12: ASM: codechicken.nei.ServerHandler@dfbe02d tickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 13: ASM: cofh.mod.updater.UpdateManager@48a23da4 tickStart(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 14: ASM: thaumic.tinkerer.common.potion.PotionEffectHandler@5127bc57 onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 15: ASM: twilightforest.TFTickHandler@666d27a2 playerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 16: ASM: morph.common.core.TickHandlerServer@5a4d5316 playerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 17: ASM: openblocks.common.ServerTickHandler@6fa63661 onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 18: ASM: com.rwtema.extrautils.worldgen.DarknessTickHandler@23289883 tickStart(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 19: ASM: com.forgeessentials.util.events.ForgeEssentialsEventFactory@41815117 playerTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 20: ASM: vazkii.botania.common.block.BlockPistonRelay@55471380 tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 21: ASM: com.sk89q.worldedit.forge.ThreadSafeCache@22af989e tickStart(Lcpw/mods/fml/common/gameevent/TickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 22: ASM: appeng.hooks.TickHandler@6d340d97 onTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 23: LOWEST
11:40:25 PM CONSOLE: thread/ERROR] [FML]: 24: ASM: vazkii.botania.common.item.ItemRegenIvy@13c99670 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
11:40:25 PM CONSOLE: thread/WARN]: Failed to handle packet for /192.168.2.113:57660
11:40:26 PM CONSOLE: mercsniper has left.
11:40:26 PM CONSOLE: [INFO] mercsniper lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
11:40:26 PM CONSOLE: [INFO] mercsniper left the game

**Comment by olee** [comment] 2015-02-01 12:04
What did you do to get this error? (That you moved your player is obvious, but what else?)

OT: Come on use code-blocks for those logs.... just put ```` above and below your log!

**Comment by ultrasn0w** [comment] 2015-02-01 19:30
I'm experiencing the same Issue, but I haven't moved at all, it's directly after joining my Server, and I get kicked right away.

Log:
http://pastebin.com/1V6MQU60

I haven't done anything than installing ForgeEssientals and then trying to connect.

**Comment by mercsniper** [comment] 2015-02-01 19:41
My apologies, Didn't know about code blocks. I installed it in my server with the client package, connected to the server, and approximately 3 - 4 seconds after joining the server, it crashes to "internal Error" any movement of the mouse or player causes it to occur faster.

**Comment by liach** [comment] 2015-02-03 04:21
https://github.com/ForgeEssentials/ForgeEssentialsMain/blob/develop/src/main/java/com/forgeessentials/worldborder/ModuleWorldBorder.java#L159

**Comment by luacs1998** [comment] 2015-02-03 04:26
@olee broke something when he ported to the new datasaving system...

**Comment by olee** [comment] 2015-02-03 09:54
You should know better, that I currently don't have time @luacs1998 :disappointed: 
Please take care of that small `if (border != null) { ... }` check.
Also it's not because of new data-backend, but because of that weird way borders are managed and expected to exist for every zone. you might want to remove [line 183-186](https://github.com/ForgeEssentials/ForgeEssentialsMain/blob/develop/src/main/java/com/forgeessentials/worldborder/ModuleWorldBorder.java#L183-L186) and implement proper checks, if any world-border was set.

**Comment by liach** [comment] 2015-02-03 20:40
It seems that both serverzone and worldzone shouldn't be null. Maybe one was setup in startup the other one doesn't.

**Comment by luacs1998** [comment] 2015-02-04 02:31
I would fix it if I knew what the code you removed did...

**Comment by olee** [comment] 2015-02-04 10:53
I told you I didn't remove code there.
The problem was there before I even did anything to that code (as part of new permissions).
It's because whover wrote this *** enforced a condition that for each zone there **must** be an entry in `borderMap`.

But now that I take another look at it, it's even worse.
The zones are references by (the non unique) names instead of their IDs.
The whole thing needs to be fixed.

**Comment by mercsniper** [comment] 2015-02-04 18:33
If I knew anything about programming java or how minecraft modding worked, I would assist, but I appreciate your assistance gents.

**Comment by liach** [comment] 2015-02-04 19:17
The method checks both server zone and world zone border. Maybe there's no exception handling on one of them.

**Comment by cri5ti** [comment] 2015-02-05 17:44
It's a duplicate of #1256.
This comment should get you running https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1256#issuecomment-72345857 until a fix is available.

**Closed** 2015-02-06 03:35 UTC

**Comment by tallboy2k7** [comment] 2015-02-06 21:05
So the fix posted there worked for Overworld- but this is doing it for Nether/Twilight ect aswell. Would ya mind pointing me in the direction of fixing that?

**Comment by goreacraft** [comment] 2015-02-07 14:04
tallboy2k7 - just repeat the same workaround for all other dimennsions
