### ISSUE TITLE
[Major] Permissions failure while server running / loss of player data

### ISSUE THREAD

**Issue by Paul17041993** [ForgeEssentials/ForgeEssentialsMain#1517] opened 2015-05-21 21:49 UTC
Server was perfectly fine the previous night, but log in this morning to find the permissions system had a complete failure and was giving everyone OP permissions, both of which are severe faults.

- in the case of a fatal permissions error, everyone should default to either standard vanilla perms, or deny-all, and should cause the server to crash anyway. Letting the server run with everyone as an OP is extremely bad.

all that can be seen in the logs is that the 'saving permissions' spam (from #1491 / #1403) simply stops, no error presented in any logs, unable to test recent builds due to #1489.

update; any player that logged in during the failure resulted in their permissions being forcefully assigned to _FAKEPLAYERS_, which means that their files need fixing by removing said line or delete the player permission files entirely.

**Comment by Paul17041993** [comment] 2015-05-21 22:23
This has also resulted in a permanent failure of the backup system AND player data being forcefully reset to the oldest backup, the actual player data itself is fine but FE keeps forcefully replacing it, resulting in me now having to run the server with FE disabled until its fixed.

**Comment by olee** [comment] 2015-05-22 05:25
I think I did tell you about #1489 to **disable playerlogger** for now to get it running.

Do you have any logs for your failure?
It's quite interesting that players got assigned to the FakePlayer group...
It's probably the fault of a mod creating FakePlayers with the UUID of the players themselves.
For now you can circumvent this by configuring the FakePlayer group permissions to use `fe.protection.* = true` instead of old default `* = true`.

**Comment by Paul17041993** [comment] 2015-05-22 06:31
- As already stated, there's nothing in the logs of any errors or exceptions, just that the 'saving permissions' stops and gets replaced with the saving world messages.
- List of mods is identical to #1489.
- I was the last one off, first one on, was forced assigned to _FAKEPLAYERS_ by FE for an unknown reason, again no errors, exceptions or simple messages as to why.
- cant be a mod as the server was running for almost a week straight to only suddenly occur after the day ticked over at midnight (US box time), nothing printed.

the biggest kicker at this point though is that both the backup system is 'dead', ie it no longer backs up the worlds correctly anymore, and FE will keep replacing the player data with ones since about a week ago, no messages as to why either except for the 'cant delete file' errors from the backup bug.

**Comment by olee** [comment] 2015-05-22 06:40
> List of mods is identical to #1489.

 - You never posted a list of your mods - even in #1489  
  At least I could not find one
 - Does the issue still persist or does everything work correctly after a server restart again?  
  (Of course after removing the players from FakePlayer group)
 - Did you already try latest version **[with disabled PlayerLogger](https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1489#issuecomment-103179100)**?  
  This one should boot even if it cannot load hibernate
 - It would help a lot if you could come onto our IRC channel #forgeessentials on http://esper.net.
  I might be able to help you more with this issue and #1489 then

**Comment by Paul17041993** [comment] 2015-05-22 07:02
- I'm pretty sure at least one of the many logs I posted in #1489 had the list, but here you go;
[18:04:13] [Netty IO #2/INFO] [FML/]: Client attempting to join with 90 mods : MineFactoryReloaded|CompatForgeMicroblock@1.7.10R2.8.0,MineFactoryReloaded|CompatRailcraft@1.7.10R2.8.0,MineFactoryReloaded|CompatMystcraft@1.7.10R2.8.0,HungerOverhaul@1.7.10-beta.6.jenkins70,OpenPeripheralIntegration@0.2.2,BuildCraft|Transport@6.4.14,TwilightForest@2.3.5,WailaHarvestability@1.1.2,ironchestminecarts@1.0.2,mcp@9.05,RotaryCraft@Gamma,funkylocomotion@1.0,NEIAddons|Forestry@1.12.5.17,NEIAddons|CraftingTables@1.12.5.17,NEIAddons|ExNihilo@1.12.5.17,Thaumcraft@4.2.3.5,thaumcraftneiplugin@1.7.10-1.7,Forestry@3.5.4.13,TConstruct@1.7.10-1.8.5.build957,EnderStorage@1.4.7.33,<CoFH ASM>@000,OpenPeripheral@0.3.1,<DragonAPI ASM>@0,RedstoneArsenal@1.7.10R1.1.0,appliedenergistics2@rv2-beta-31,MineFactoryReloaded|CompatAtum@1.7.10R2.8.0,IronChest@6.0.62.742,ProjRed|Transmission@4.6.0.79,DragonAPI@1.0,CodeChickenCore@1.0.6.43,MineFactoryReloaded|CompatThermalExpansion@1.7.10R2.8.0,ProjRed|Transportation@4.6.0.79,BuildCraft|Energy@6.4.14,Railcraft@9.6.1.0,moreplayermodels@1.7.10b,appliedenergistics2-core@rv2-beta-31,ThermalDynamics@1.7.10R1.0.0,NEIAddons@1.12.5.17,ChickenChunks@1.3.4.19,ProjRed|Integration@4.6.0.79,CarpentersBlocks@3.3.6,Waila@1.5.10,CoFHCore@1.7.10R3.0.2,ProjRed|Core@4.6.0.79,MineFactoryReloaded|CompatAppliedEnergistics@1.7.10R2.8.0,ProjRed|Illumination@4.6.0.79,MineFactoryReloaded@1.7.10R2.8.0,journeymap@5.0.1,ProjRed|Expansion@4.6.0.79,ThermalExpansion@1.7.10R4.0.1,MineFactoryReloaded|CompatBackTools@1.7.10R2.8.0,MineFactoryReloaded|CompatProjRed@1.7.10R2.8.0,inventorytweaks@1.58-147-645ca10,BuildCraft|Silicon@6.4.14,MineFactoryReloaded|CompatIC2@1.7.10R2.8.0,OpenPeripheralCore@1.1.1,MineFactoryReloaded|CompatVanilla@1.7.10R2.8.0,ProjRed|Compatibility@4.6.0.79,GraviSuite@1.7.10-2.0.3,MineFactoryReloaded|CompatThaumcraft@1.7.10R2.8.0,FML@7.10.130.1395,BuildCraft|Core@6.4.14,NEIAddons|Botany@1.12.5.17,NotEnoughItems@1.0.4.105,IC2@2.2.718-experimental,ForgeMultipart@1.1.2.334,MineFactoryReloaded|CompatExtraBiomes@1.7.10R2.8.0,Baubles@1.0.1.10,ExtrabiomesXL@3.16.2,neiintegration@1.0.9,Mantle@1.7.10-0.3.2.jenkins184,OpenMods@0.7.2,ComputerCraft@1.73,MineFactoryReloaded|CompatChococraft@1.7.10R2.8.0,OpenModsCore@0.7.2,MineFactoryReloaded|CompatTwilightForest@1.7.10R2.8.0,BuildCraft|Factory@6.4.14,Forge@10.13.3.1395,MineFactoryReloaded|CompatBuildCraft@1.7.10R2.8.0,MineFactoryReloaded|CompatForestry@1.7.10R2.8.0,MineFactoryReloaded|CompatSufficientBiomes@1.7.10R2.8.0,McMultipart@1.1.2.334,BetterFoliage@1.0.11,ForgeMicroblock@1.1.2.334,ProjRed|Exploration@4.6.0.79,AppleCore@1.1.0,MrTJPCoreMod@1.0.6.13,BuildCraft|Builders@6.4.14,MineFactoryReloaded|CompatTConstruct@1.7.10R2.8.0,ThermalFoundation@1.7.10R1.0.0
[18:04:13] [Netty IO #2/INFO] [FML/]: Attempting connection with missing mods [Dynmap, ForgeEssentials, worldedit] at CLIENT

- due to the modificication/corruption of the player permissions and data on FE's side, no, a server restart fixed nothing and in fact made it worse as it then started the player data replacement, including inventory and beds.
- trying now, it at least booted but some things In previous issues are still broken, I also purged the libraries, replaced the FE data with that from a backup the day before and repaired and cleaned each individual player permission file to just have the name and uuid lines.
- busy enough as-is to add another IRC channel to my list, rather post the issues as they come on github as that's what its for.

**Comment by Paul17041993** [comment] 2015-05-22 07:19
Backup system is still broken even with the latest build, except there's now nothing at all in the logs about it except for the following supposed leaks;
http://pastebin.com/CZaN9dij

all that happens during a backup is the creation of an invalid zip file 5-7MB in size, which is the exact same as to what it was doing after the reboot with beta6.

**Comment by Paul17041993** [comment] 2015-05-22 07:31
and now a permission reload wiped player inventories...

**Comment by olee** [comment] 2015-05-22 10:56
If you updated to an FE build from 585 to 594, then it was my fault.
There was a bug causing saving of some player-data to fail (which will make FE unable to read corrupted files),
However this can in no way affect player inventories, which we do not access at all.
I suppose you either have some really weird setup or something else is going on there as I was not able to replicate any of these issues so far and no one else reported them.
I will still try my best to find the reason though.

**Comment by luacs1998** [comment] 2015-05-23 01:01
Try checking your hard drive and all that - there may be some disk corruption going on.

**Comment by Paul17041993** [comment] 2015-05-23 09:02
would have noticed if it were the disks, this was on the US linux box with its dual 2TB RAID1.

**Comment by luacs1998** [comment] 2015-05-23 09:23
Try with build 612 - should fix your PL classloading issues.

I can only suspect that file corruption, or incorrect permissions or something else is going on - this does not happen under normal circumstances. It could be that the persistence backend doesn't support RAID arrays, or some other reason.

FE does not touch player inventories, so if your inventories are also getting corrupted, then the problem is probably on your side.

We can't help you without having access to your server to identify the issues, so I'll just mark it as a pending issue until you can identify what's going on.

**Comment by Paul17041993** [comment] 2015-05-23 09:32
I'm still unsure about when it was reverting player data to the oldest backups/last reboot, however after disabling FE that time it stopped occurring.
FE clearing inventories though was definitely a bug in the FE permissions system, when using the feperm reload command all items and blocks were denied to all player inventories, and as such it deleted everything that anyone had, excluding anything in the world or chests etc. But this seems to only occur on the reload.
Since then the server was reverted to a special backup just before FE was re-enabled, and FE has been disabled since, however I cant test any recent builds just yet as there currently seems to be a backbone issue between me and the US...

**Comment by olee** [comment] 2015-05-23 16:08
Deleted all items?
Sounds much like you used a `* = false` rule in your permissions.
This is very dangerous as for example `fe.protection.exist.<itemname>` permissions will delete items from the world if denied (item banning).

**Comment by Paul17041993** [comment] 2015-05-23 22:43
You're expecting a deny-default policy to behave differently...? The only reason why I have permissions manually denied by default is because FE tends to leave a lot of dangerous commands etc to allow by default, whereas I only ever want to allow what I put in my permission groups. Deny-default has been the standard for many permission systems virtually everywhere, simply because it's the most secure and makes perfect sense.

The actual problem though was that FE was applying the permissions before they were fully reloaded, which is only a new bug as it didn't exist in beta6 and I don't think it was in earlier beta7 builds either.

**Comment by olee** [comment] 2015-05-24 16:51
What I am telling you is not that deny-default policy is bad or we do not support it.
It is just that it is very complicated to set up as there are a lot of important permissions that need to be configured correctly for this to work.

> The actual problem though was that FE was applying the permissions before they were fully reloaded, which is only a new bug as it didn't exist in beta6 and I don't think it was in earlier beta7 builds either.

This cannot happen, because FE loads all permissions and then replaces the old permission tree.
What could have happened however, is that the permissions have not been properly saved before.
This is an issue I am aware of and I intend to fix soon.
It can especially happen, if some other program keeps a lock on any file in the `world/FEData/permissions` folder.

**Comment by Paul17041993** [comment] 2015-05-24 21:38
In the case of a file load/parse failure of any sort, the reload should abort and leave the permissions unchanged.

**Comment by olee** [comment] 2015-05-24 22:04
As I said the *saving* failed which makes the *loading* unable to detect this

**Comment by Paul17041993** [comment] 2015-05-24 23:56
you mean saving as in saving the permissions to file? or are you confusing it with applying to the permissions system?

**Comment by olee** [comment] 2015-05-25 10:10
I mean saving the permissions to file.
The code for this currently deletes the whole permissions directory and then writes all permissions again.
However it can sometime happen, that it can only delete a part of the permission directory and then fails without writing the permissions to file again.
When it tries to load permissions again then, it will only find some files without knowing that.
That is why I said I will fix this sometime.

Also, if you want to edit permissions externally - especially for that reason - I suggest you disable autosave first with `/p save disable`.

**Comment by luacs1998** [comment] 2015-06-07 03:52
I have not heard anything from this - assuming it's not an issue, so closing.

**Closed by luacs1998** 2015-06-07 03:52 UTC
Labels: pendingaction

**Comment by Paul17041993** [comment] 2015-06-07 07:50
I haven't re-enabled FE simply because I cant risk it messing everything up again...

**Comment by luacs1998** [comment] 2015-06-07 08:29
Make a copy of your server and try with the latest build.

**Comment by melekaiah** [comment] 2015-06-07 10:56
Im gonna try with the latest this coming week. I did ha e proble.s with permissions breaking. But client relog fixed that
