### ISSUE TITLE
Forge Essentials Permissions Based on Items / Blocks Issues.

### ISSUE THREAD

**Issue by KaneHart** [ForgeEssentials/ForgeEssentialsMain#1463] opened 2015-04-29 05:11 UTC
I'm having a hard time banning items in FE. I'm going to actually show you something really basic and that is Vanilla TNT. For some reason I can't ban it's placement.

Originally we had this I'm not sure if it worked I think it did:
fe.protection.place.tile.tnt=false
I also tried
fe.protection.place.tile.tnt.0=false

This is what the /itemperm comes up with
tile.tnt.0

I also had more complex issues with other mods. Using the same names multiple times and not having more detailed metadata or maybe it's another term for it. I tried finding a example but maybe this issue has been fixed now.

Thanks.

**Comment by olee** [comment] 2015-04-29 05:39
Which is why I told you that I am planning to change a bit of the permission handling!

Currently items are identified by `itemStack.getUnlocalisedName()` which could literally return anything **and in some mod's blocks / items even returns null** which regularly caused some crashes in the past.

This is why the plan is to change this to `GameData.getItemRegistry().getNameForObject(item)` which returns the correct unique identifier.
Also `/p` command is going to get a subcommand for banning items easily which will also have a global shortcut like for example `/banitem`.

**Comment by olee** [comment] 2015-04-29 17:14
The issue with protection permissions not working should be solved by this now.

What's left is to add an easier-to-use permission management command for protection (e.g. `/banitem`)

**Comment by KaneHart** [comment] 2015-04-30 07:09
Thanks. I wanted to talk about easy permission usage. I for one don't ban a lot of items. Some them are permission based as in some can use it some can't. Also quite a few them I might just make it so they can't place it on the ground. Clearly workarounds but that is fine.

So for example 

I would type /itemperm (broken right now) on tnt and get tile.tnt
So in the permissions file if this was actually correct I by hand type in the following:
fe.protection.place.blockITNT=false


Now if it's an item I for sure want to block say Nuke has no uses for me in crafting I would add it to the permissions like so:
fe.protection.place.blockBUKE=false
fe.protection.place.blockNuke.*=false
fe.protection.interact.blockNuke.*=false
fe.protection.inventory.ic2.nukeitemnotsuretherealone.*=false

The idea here is I want to prevent them from picking it up using it etc.

Now if you want to make my life easier and many others you can add 1 line support. You said 5-6 months ago this would not be possible. Maybe this has changed now but I would love to have say break|place|interact in 1 single line.



Anyways Please fix /itemperm we can't do anything without it since many items don't actually always have proper names etc. Makes it really messy.

**Comment by olee** [comment] 2015-04-30 08:55
`/itemperm` was only broken for maybe an hour until I realized it.
If you updated to latest version, it should work perfectly.

About combining (`break`, `place`, `interact`) permissions and (`use`, `inventory`), I am sorry to disappoint you but without some more testing I still have to tell you that we cannot do that.

The problem is that making a permission like `fe.protection.ban.<block>` would mean we need to run **two** permission checks on each place or break event, doubling the strain on the server for these events. So when we compare the two possibilities:
 - less leg for the server, and
 - the need to set up more permissions,
it is obvious that the second choice is better.

Or do you want your server to start lagging just for a permission to make things easier for you?

I hope you understand what I want to tell you.

**Comment by KaneHart** [comment] 2015-04-30 09:17
Hmm lag ;)? Nah

Also the /itemperm does not work I'm using 3896dbc4d4f06c481cf3670dcd463cd6 server that is 546

screenshot what I see: http://i.imgur.com/Z31LBZ5.png

If I type in my first permissions related anything into chat I also see this one time and never again:

[05:16:35] [Server thread/WARN] [FML]: =============================================================
[05:16:35] [Server thread/WARN] [FML]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[05:16:35] [Server thread/WARN] [FML]: Offendor: antlr/Parser.panic()V
[05:16:35] [Server thread/WARN] [FML]: Use FMLCommonHandler.exitJava instead
[05:16:35] [Server thread/WARN] [FML]: =============================================================

**Comment by olee** [comment] 2015-04-30 10:43
This is a because of Hibernate library iirc and does not really cause any problem - it's just a warning.
As for `/itemperm` I will see to fix it.

**Comment by KaneHart** [comment] 2015-05-02 02:27
Doing some more testing. Things are working well found a major bug that I don't see myself but with another player who drops items inventory ban the items chase them around and follow them lol..

The iTNT and the firestone from RC in this picture keeps sort of spawing and dropping from him over and over...

http://i.imgur.com/8CSX2Oy.jpg

**Comment by olee** [comment] 2015-05-03 04:26
Yeah the thing is that inventory permissions should not just outright destroy items.
For example if a player enters an area where some items are banned, he should still be allowed to go outside to pick them up again.
I might add a new permission to also allow direct destruction of these items instead of dropping them.

**Comment by olee** [comment] 2015-05-05 18:08
As I see no more problem with this one, I'm closing it.

**Closed by olee** 2015-05-05 18:08 UTC
Labels: request
