### ISSUE TITLE
Mariculture incompability

### ISSUE THREAD

**Issue by Cuppycake** [ForgeEssentials/ForgeEssentialsMain#1333] opened 2015-03-09 00:28 UTC
Upgrading from build 413 to build 428
Server has ran fine with all previous versions of FE

http://pastebin.com/WBUM0iLa

Thanks for taking a look.

**Comment by Ganjalf-Amsterdoom** [comment] 2015-03-09 10:35
I can confirm this and:

java.lang.RuntimeException: java.lang.ClassNotFoundException: cpw.mods.fml.common.asm.FMLSanityChecker

When forge essentials is removed from server everything boot fine.

Thank you for your time guys

**Comment by olee** [comment] 2015-03-09 11:06
I am unable to reproduce this in the IDE.
This could take a little while to figure out...

**Comment by Cuppycake** [comment] 2015-03-09 16:02
We do weekly updates and pretty much anything that can be updated stays updated in the pack.
I do remember trying to upgrade to build 415 and getting this problem and I thought it was the recent issues with CoFH so I just waited it out. So I don't know if that could be a starting point for you.

Server is running on 
java version "1.7.0_75"

In the mean time Ill go back and tinker with some updates and mods on my test server.

**Comment by olee** [comment] 2015-03-14 10:55
Any updates on this one?
Does the error still occur with latest FE?

**Comment by Cuppycake** [comment] 2015-03-14 17:43
No change using newest FE build. Same error on my PC and linux box. CoFH mods are all updated to latest.

**Comment by LightningLdr180** [comment] 2015-03-18 06:30
Wanted to chime in that I have the same issue.  Latest builds all crash with the same errors as OP.
http://pastebin.com/pt50xngL

**Comment by luacs1998** [comment] 2015-03-18 12:08
Not sure what exactly is going on, so I'll have to apologize for troubling you again, @mumfrey...

**Comment by shortybsd** [comment] 2015-03-18 14:49
Fixed it and found out the issue! Do not add a user to the permissions system if the user has never connected to the server. It is pretty much right in the error log, the UID could not be looked up.
I removed all the people i am expecting to join my server today before they logged in. I removed all their files and boom loads perfect.

**Comment by olee** [comment] 2015-03-18 14:52
This is a different issue than your NullPointerException.
This is about the problem with FMLSanityChecker.

**Comment by mindcloud69** [comment] 2015-03-21 16:03
I am getting the FMLSanityChecker error as well.

**Comment by LightningLdr180** [comment] 2015-03-28 06:13
Tried using a different version of java to no avail.  I also updated forge to 10.13.2.1343, with no change in the issue.

**Comment by luacs1998** [comment] 2015-03-28 06:34
I need full crash reports, mods used, etc. Only then can I come up with a suitable workaround.

**Comment by LightningLdr180** [comment] 2015-03-28 06:54
I think I have finally found something.  I tried it with a fresh server, then started adding mods one at a time until it would no longer load.  When Mariculture is present, then the issue occurs.  This does not happen with beta-5 for Forge Essentials, only the beta-6 versions.

http://pastebin.com/Bkne2FBf

**Comment by luacs1998** [comment] 2015-03-28 07:43
Excellent, thanks a lot for the help.

Time to break out my decompiler...

**Comment by luacs1998** [comment] 2015-03-28 09:40
Forget it, I'll just put up an incompatibility warning.

For the record, I officially declare FE **INCOMPATIBLE** with mariculture until this issue can be dealt with.

**Comment by Ganjalf-Amsterdoom** [comment] 2015-03-28 12:11
For the record, thank you so much for your time luacs and olee. \o

**Comment by LightningLdr180** [comment] 2015-03-28 15:40
Thank you lucas! I will try to take the issue up with joshiejack for Mariculture and see if maybe they are doing something that might cause an issue with FML and FE.

**Comment by liach** [comment] 2015-04-23 01:11
@ForgeEssentials/Developers Is this still an issue since mixin's update? Or try to update mixin again?

**Comment by luacs1998** [comment] 2015-04-23 02:52
I need to do some testing in this regard.

**Comment by luacs1998** [comment] 2015-04-26 02:08
Merged into #1449

**Closed by luacs1998** 2015-04-26 02:08 UTC
Labels: bug, modcompat

**Comment by Ganjalf-Amsterdoom** [comment] 2015-05-14 13:34
Cannot test, the mod still does not boot and crash with fml sanity check error.
