### ISSUE TITLE
Fastcraft incompability

### ISSUE THREAD

**Issue by Mistercl0ud** [ForgeEssentials/ForgeEssentialsMain#1386] opened 2015-04-09 14:11 UTC
Hello, since the installation of forgeessentials-1.7.10-1.4.0-beta6-server my game crashes on startup :
````
[10:07:42] [main/INFO]: Loading tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[10:07:42] [main/INFO]: Using primary tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[10:07:42] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[10:07:42] [main/INFO]: Calling tweak class com.mumfrey.liteloader.launch.LiteLoaderTweaker
[10:07:42] [main/INFO]: Bootstrapping LiteLoader 1.7.10
[10:07:42] [main/INFO]: Registering API provider class com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient
[10:07:42] [main/INFO]: Spawning API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' ...
[10:07:42] [main/INFO]: API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' provides API 'liteloader'
[10:07:42] [main/INFO]: Initialising API 'liteloader' ...
[10:07:42] [main/INFO]: LiteLoader begin PREINIT...
[10:07:42] [main/INFO]: Initialising Loader properties...
[10:07:42] [main/INFO]: Setting up logger...
[10:07:42] [main/INFO]: LiteLoader 1.7.10_04 starting up...
[10:07:42] [main/INFO]: Java reports OS="windows 7"
[10:07:42] [main/INFO]: Enumerating class path...
[10:07:42] [main/INFO]: Class path separator=";"
[10:07:42] [main/INFO]: Class path entries=(
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\com\mumfrey\liteloader\1.7.10\liteloader-1.7.10.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.11\launchwrapper-1.11.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\16.0\guava-16.0.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\net\minecraftforge\forge\1.7.10-10.13.3.1358-1.7.10\forge-1.7.10-10.13.3.1358-1.7.10.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.11\launchwrapper-1.11.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\com\typesafe\config\1.2.1\config-1.2.1.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2\scala-continuations-library_2.11-1.0.2.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2\scala-continuations-plugin_2.11.1-1.0.2.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\lzma\lzma\0.0.1\lzma-0.0.1.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.3.5\realms-1.3.5.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\java3d\vecmath\1.3.1\vecmath-1.3.1.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.10.Final\netty-all-4.0.10.Final.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\16.0\guava-16.0.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.2.1\commons-lang3-3.2.1.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.16\authlib-1.5.16.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.1\lwjgl-2.9.1.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.1\lwjgl_util-2.9.1.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\libraries\tv\twitch\twitch\5.16\twitch-5.16.jar
   classpathEntry=C:\Users\Luc\AppData\Roaming\.minecraft\versions\1.7.10\1.7.10.jar
)
[10:07:42] [main/INFO]: Registering discovery module EnumeratorModuleClassPath: [<Java Class Path>]
[10:07:42] [main/INFO]: Registering discovery module EnumeratorModuleFolder: [C:\Users\Luc\AppData\Roaming\.minecraft\mods]
[10:07:42] [main/INFO]: Registering discovery module EnumeratorModuleFolder: [C:\Users\Luc\AppData\Roaming\.minecraft\mods\1.7.10]
[10:07:42] [main/INFO]: Adding supported mod class prefix 'LiteMod'
[10:07:42] [main/INFO]: Discovering tweaks on class path...
[10:07:42] [main/INFO]: Discovering valid mod files in folder C:\Users\Luc\AppData\Roaming\.minecraft\mods
[10:07:42] [main/INFO]: Considering valid mod file: C:\Users\Luc\AppData\Roaming\.minecraft\mods\mod_Autofish_0.4.9_mc1.7.10.litemod
[10:07:42] [main/INFO]: Considering valid mod file: C:\Users\Luc\AppData\Roaming\.minecraft\mods\mod_voxelMap_1.5.9b_for_1.7.10.litemod
[10:07:42] [main/INFO]: Considering valid mod file: C:\Users\Luc\AppData\Roaming\.minecraft\mods\MouseTweaks-2.4.4-mc1.7.10.jar
[10:07:42] [main/INFO]: Adding newest valid mod file 'C:\Users\Luc\AppData\Roaming\.minecraft\mods\mod_Autofish_0.4.9_mc1.7.10.litemod' at revision 39.0000
[10:07:42] [main/INFO]: Adding newest valid mod file 'C:\Users\Luc\AppData\Roaming\.minecraft\mods\mod_voxelMap_1.5.9b_for_1.7.10.litemod' at revision 1509.0000
[10:07:42] [main/INFO]: Adding newest valid mod file 'C:\Users\Luc\AppData\Roaming\.minecraft\mods\MouseTweaks-2.4.4-mc1.7.10.jar' at revision 184.0000
[10:07:42] [main/INFO]: Discovering valid mod files in folder C:\Users\Luc\AppData\Roaming\.minecraft\mods\1.7.10
[10:07:42] [main/INFO]: Searching for tweaks in 'Baubles-1.7.10-1.0.1.10.jar'
[10:07:42] [main/WARN]: Error parsing manifest entries in 'C:\Users\Luc\AppData\Roaming\.minecraft\mods\1.7.10\Baubles-1.7.10-1.0.1.10.jar'
[10:07:42] [main/INFO]: Searching for tweaks in 'CodeChickenLib-1.7.10-1.1.1.99-universal.jar'
[10:07:42] [main/WARN]: Error parsing manifest entries in 'C:\Users\Luc\AppData\Roaming\.minecraft\mods\1.7.10\CodeChickenLib-1.7.10-1.1.1.99-universal.jar'
[10:07:42] [main/INFO]: Searching for tweaks in 'ForgeMultipart-1.7.10-1.1.0.309-universal.jar'
[10:07:42] [main/WARN]: Error parsing manifest entries in 'C:\Users\Luc\AppData\Roaming\.minecraft\mods\1.7.10\ForgeMultipart-1.7.10-1.1.0.309-universal.jar'
[10:07:42] [main/INFO]: Searching for tweaks in '[1.7.10]bspkrsCore-universal-6.16.jar'
[10:07:42] [main/WARN]: Error parsing manifest entries in 'C:\Users\Luc\AppData\Roaming\.minecraft\mods\1.7.10\[1.7.10]bspkrsCore-universal-6.16.jar'
[10:07:42] [main/INFO]: Mod file 'mod_Autofish_0.4.9_mc1.7.10.litemod' provides classTransformer 'troy.autofish.PacketEntityVelocityTransformer', adding to class loader
[10:07:42] [main/INFO]: classTransformer 'troy.autofish.PacketEntityVelocityTransformer' was successfully added
[10:07:42] [main/INFO]: Mod file 'mod_voxelMap_1.5.9b_for_1.7.10.litemod' provides classTransformer 'com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer', adding to class loader
[10:07:42] [main/INFO]: classTransformer 'com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer' was successfully added
[10:07:42] [main/INFO]: LiteLoader PREINIT complete
[10:07:42] [main/INFO]: Sorting registered packet transformers by priority
[10:07:42] [main/INFO]: Added 0 packet transformer classes to the transformer list
[10:07:42] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.transformers.event.EventProxyTransformer'
[10:07:42] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.launch.LiteLoaderTransformer'
[10:07:42] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.client.transformers.CrashReportTransformer'
[10:07:42] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer'
[10:07:42] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer'
[10:07:42] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer'
[10:07:42] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[10:07:42] [main/INFO]: Forge Mod Loader version 7.10.104.1358 for Minecraft 1.7.10 loading
[10:07:42] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 7:amd64:6.1, installed at G:\Program Files\Minecraft\runtime\jre-x64\1.8.0_25
[10:07:43] [main/INFO]: [AppEng] Core Init
[10:07:43] [main/WARN]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:07:43] [main/INFO]: [codechicken.core.launch.DepLoader$DepLoadInst:checkExisting:436]: Warning: version of bspkrsCore, 6.16 is newer than request 6.15
[10:07:43] [main/WARN]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:07:43] [main/WARN]: The coremod fastcraft.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:07:43] [main/INFO]: Loading tweaker com.forgeessentials.core.preloader.FELaunchHandler from forgeessentials-1.7.10-1.4.0-beta6-server.jar
[10:07:43] [main/WARN]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:07:43] [main/WARN]: The coremod pcl.lc.coremod.LCCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:07:43] [main/INFO]: LCCoreMod ready for action!
[10:07:43] [main/WARN]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:07:43] [main/WARN]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:07:43] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.7.10_HD_U_B5.jar
[10:07:43] [main/WARN]: The coremod mods.flammpfeil.optinerf.asm.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:07:43] [main/INFO]: Loading tweaker shadersmodcore.loading.SMCTweaker from ShadersModCore-v2.3.28-mc1.7.10-f.jar
[10:07:43] [main/WARN]: The coremod thaumcraft.codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:07:43] [main/WARN]: The coremod thaumic.tinkerer.preloader.ThaumicTLoaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:07:43] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:07:43] [main/INFO]: Loading tweak class name com.forgeessentials.core.preloader.FELaunchHandler
[10:07:43] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[10:07:43] [main/INFO]: Loading tweak class name shadersmodcore.loading.SMCTweaker
[10:07:43] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[10:07:43] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:07:43] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:07:43] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[10:07:43] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: acceptOptions
[10:07:43] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: injectIntoClassLoader
[10:07:43] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ClassTransformer
[10:07:43] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine URL: file:/C:/Users/Luc/AppData/Roaming/.minecraft/mods/OptiFine_1.7.10_HD_U_B5.jar
[10:07:43] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ZIP file: java.util.zip.ZipFile@290222c1
[10:07:43] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:07:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    cpw/mods/fml/common/asm/transformers/EventSubscriptionTransformer.buildEvents(Lorg/objectweb/asm/tree/ClassNode;)Z @529: invokevirtual
  Reason:
    Type 'org/objectweb/asm/tree/FieldInsnNode' (current frame, stack[1]) is not assignable to 'org/objectweb/asm/tree/AbstractInsnNode'
  Current Frame:
    bci: @529
    flags: { }
    locals: { 'cpw/mods/fml/common/asm/transformers/EventSubscriptionTransformer', 'org/objectweb/asm/tree/ClassNode', 'java/lang/Class', integer, integer, integer, 'java/lang/Class', 'org/objectweb/asm/Type', 'org/objectweb/asm/Type', 'org/objectweb/asm/tree/MethodNode' }
    stack: { 'org/objectweb/asm/tree/InsnList', 'org/objectweb/asm/tree/FieldInsnNode' }
  Bytecode:
    0x0000000: 2ab6 0057 b600 5d2b b400 6010 2f10 2eb6
    0x0000010: 0064 b600 6a4d 126c 2cb6 0070 9a00 0503
    0x0000020: ac03 3e03 3604 0336 0512 7203 2ab6 0057
    0x0000030: b600 5db8 0076 3a06 1906 b800 7c3a 072b
    0x0000040: b400 80b9 0086 0100 3a08 1908 b900 8c01
    0x0000050: 0099 0095 1908 b900 9001 00c0 0092 3a09
    0x0000060: 1909 b400 9412 96b6 001b 9900 2519 09b4
    0x0000070: 0099 b200 9d03 bd00 78b8 00a1 b600 1b99
    0x0000080: 0010 1909 b400 a507 7e07 a000 0504 3e19
    0x0000090: 09b4 0094 12a7 b600 1b99 0025 1909 b400
    0x00000a0: 9919 0703 bd00 78b8 00a1 b600 1b99 0011
    0x00000b0: 1909 b400 a504 7e04 a000 0604 3604 1909
    0x00000c0: b400 9412 a8b6 001b 9900 1b19 09b4 0099
    0x00000d0: b200 9d03 bd00 78b8 00a1 b600 1b99 0006
    0x00000e0: 0436 05a7 ff67 1d99 0028 1504 9a00 21bb
    0x00000f0: 00aa 59bb 00ac 59b7 00ad 12af b600 b32b
    0x0000100: b400 b4b6 00b3 b600 b8b7 00bb bf03 ac2b
    0x0000110: b400 60b8 00be 3a08 2bb4 00c1 bb00 c359
    0x0000120: 100a 12c5 1907 b600 c801 01b7 00cb b900
    0x0000130: ce02 0057 bb00 9259 12cf 0412 a8b2 009d
    0x0000140: 03bd 0078 b800 a101 01b7 00d2 3a09 1909
    0x0000150: b400 d6bb 00d8 5910 1903 b700 dbb6 00e0
    0x0000160: 1909 b400 d6bb 00e2 5911 00b7 1908 b600
    0x0000170: e512 a8b2 009d 03bd 0078 b800 a103 b700
    0x0000180: e8b6 00e0 1909 b400 d6bb 00ea 5911 00b1
    0x0000190: b700 ebb6 00e0 1505 9a00 0f2b b400 8019
    0x00001a0: 09b9 00ce 0200 57bb 0092 5912 cf07 1296
    0x00001b0: b200 9d03 bd00 78b8 00a1 0101 b700 d23a
    0x00001c0: 0919 09b4 00d6 bb00 d859 1019 03b7 00db
    0x00001d0: b600 e019 09b4 00d6 bb00 e259 1100 b719
    0x00001e0: 08b6 00e5 1296 b200 9d03 bd00 78b8 00a1
    0x00001f0: 03b7 00e8 b600 e019 09b4 00d6 bb00 ed59
    0x0000200: 1100 b22b b400 b412 c519 07b6 00c8 b700
    0x0000210: f0b6 00e0 bb00 f259 b700 f33a 0a19 09b4
    0x0000220: 00d6 bb00 f559 1100 c619 0ab7 00f8 b600
    0x0000230: e019 09b4 00d6 bb00 ea59 1100 b1b7 00eb
    0x0000240: b600 e019 09b4 00d6 190a b600 e019 09b4
    0x0000250: 00d6 bb00 fa59 0603 0103 01b7 00fd b600
    0x0000260: e019 09b4 00d6 bb00 ff59 1100 bb19 07b6
    0x0000270: 00e5 b701 02b6 00e0 1909 b400 d6bb 00ea
    0x0000280: 5910 59b7 00eb b600 e019 09b4 00d6 bb00
    0x0000290: d859 1019 03b7 00db b600 e019 09b4 00d6
    0x00002a0: bb00 e259 1100 b719 08b6 00e5 12a7 1907
    0x00002b0: 03bd 0078 b800 a103 b700 e8b6 00e0 1909
    0x00002c0: b400 d6bb 00e2 5911 00b7 1907 b600 e512
    0x00002d0: a8b2 009d 04bd 0078 5903 1907 53b8 00a1
    0x00002e0: 03b7 00e8 b600 e019 09b4 00d6 bb00 ed59
    0x00002f0: 1100 b32b b400 b412 c519 07b6 00c8 b700
    0x0000300: f0b6 00e0 1909 b400 d6bb 00ea 5911 00b1
    0x0000310: b700 ebb6 00e0 2bb4 0080 1909 b900 ce02
    0x0000320: 0057 bb00 9259 12cf 0412 a719 0703 bd00
    0x0000330: 78b8 00a1 0101 b700 d23a 0919 09b4 00d6
    0x0000340: bb00 ed59 1100 b22b b400 b412 c519 07b6
    0x0000350: 00c8 b700 f0b6 00e0 1909 b400 d6bb 00ea
    0x0000360: 5911 00b0 b700 ebb6 00e0 2bb4 0080 1909
    0x0000370: b900 ce02 0057 04ac                    
  Stackmap Table:
    append_frame(@33,Object[#89])
    full_frame(@74,{Object[#2],Object[#44],Object[#89],Integer,Integer,Integer,Object[#89],Object[#120],Object[#136]},{})
    append_frame(@143,Object[#146])
    same_frame(@190)
    chop_frame(@227,1)
    chop_frame(@230,1)
    same_frame(@269)
    same_frame(@271)
    append_frame(@423,Object[#120],Object[#146])

[10:07:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.getDeclaredConstructors0(Native Method)
[10:07:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2663)
[10:07:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.getConstructor0(Class.java:3067)
[10:07:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.newInstance(Class.java:408)
[10:07:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[10:07:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:101)
[10:07:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[10:07:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
````

**Comment by melekaiah** [comment] 2015-04-09 15:02
yupp getting this too.
preinit running forge 1358

**Comment by luacs1998** [comment] 2015-04-09 16:06
Try removing Optifine.

**Comment by sfPlayer1** [comment] 2015-04-10 07:48
It crashes at cpw.mods.fml.common.asm.transformers.buildEvents(), line 165:
```java
method.instructions.add(new FieldInsnNode(GETSTATIC, classNode.name, "LISTENER_LIST", tList.getDescriptor()));
```

The error basically claims FieldInsnNode wouldn't be a subclass of AbstractInsnNode, although it clearly is. I can only imagine that they were loaded from different class loaders...

**Comment by groveham** [comment] 2015-04-12 14:37
I was also getting something very similar to this, copied the whole log so you can see what's going on, error is at the end of the log: http://pastebin.com/fjHeEBTq

Removed FastCraft 1.21 and the server started working fine.

**Comment by Goten87** [comment] 2015-04-13 13:54
yeah fastcraft brakes a lot more mods then just FE
it also brakes/not load mystcraft nei plugin

**Comment by Bitterholz** [comment] 2015-04-13 16:40
I imagine rather than Fastcraft being the offendor here, it could be a problem that somebody uses a different Classloader like @sfPlayer1 allready stated.

**Comment by luacs1998** [comment] 2015-04-13 17:03
Yes, I know what is going on, seems like the only fix is to have mixins upstream shade a ASM library...

**Comment by BobertTheThird** [comment] 2015-04-14 17:10
I also have this issue with FTB Infinity 1.4.1 (issue did not exist with FTB Infinity 1.3.4) presumably because of a Fastcraft update. The crash does blame a different object than those referenced above, probably something to do with load order.

**Comment by luacs1998** [comment] 2015-04-16 13:04
Dupe of #1372

**Closed by luacs1998** 2015-04-16 13:04 UTC
Labels: modcompat
