### ISSUE TITLE
Sponge compatibility derps

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentialsMain#1689] opened 2015-08-10 02:02 UTC
https://github.com/SpongePowered/Sponge/issues/324

````
[19:39:55] [main/INFO]: Calling tweak class com.forgeessentials.core.preloader.FELaunchHandler
[19:39:55] [main/ERROR]: Unable to launch
java.lang.IllegalStateException: MixinBootstrap.register() called before MixinBootstrap.preInit()
at org.spongepowered.asm.launch.MixinBootstrap.register(MixinBootstrap.java:156) ~[sponge.jar:1.8-1499-2.1DEV-544+unknown-b544.git-unknown]
at org.spongepowered.asm.launch.MixinTweaker.acceptOptions(MixinTweaker.java:103) ~[sponge.jar:1.8-1499-2.1DEV-544+unknown-b544.git-unknown]
at com.forgeessentials.core.preloader.FELaunchHandler.acceptOptions(FELaunchHandler.java:76) ~[forgeessentials-1.8-1.8.0.21-server.jar:?]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:113) [launchwrapper-1.9.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [forge-1.8-11.14.3.1499.jar:?]
at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [forge-1.8-11.14.3.1499.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
at org.spongepowered.launch.handlers.RunHandler.run(RunHandler.java:85) 
````

@mumfrey: Is this a case of priority or conflict of interest?

**Comment by Mumfrey** [comment] 2015-08-10 10:56
It's likely to be fixed in the fix for SpongePowered/Mixin#59 I've been working on, currently I'm aware that it doesn't work as intended.

**Comment by liach** [comment] 2015-08-23 04:10
[Your derp] (https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/1256009ca5362a2afcf2b3a268f964e23494d55b)

**Comment by luacs1998** [comment] 2015-08-23 04:11
@liach I am not in a good mood, do't even try -.-

**Closed** 2015-08-23 04:14 UTC
Labels: mod-compatibility
