### ISSUE TITLE
Return Of Fastcraft Issue? - Wierd Issues With Fastcraft

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentialsMain#1423] opened 2015-04-19 23:47 UTC
Okay I posted this on their site but I am curious of anyone else has any of these issues when using fastcraft. https://drive.google.com/file/d/0B1fY2sKXiHd7YW4tOTlkN013Tm8/view?usp=sharing Please read carefully.

**Comment by olee** [comment] 2015-04-19 23:49
Duplicate of #1372

**Closed by olee** 2015-04-19 23:49 UTC
