### ISSUE TITLE
can't create/break nether portal

### ISSUE THREAD

**Issue by jaz000** [ForgeEssentials/ForgeEssentialsMain#1579] opened 2015-06-14 22:10 UTC
weird one, took me a while to work out which mod(s) might be involved

creating a portal it just sets fire to the obsidian block
breaking a portal the client gets disconnected from the server with "internal server error"
same in both overworld and nether
existing portals work fine though

I am running build 677 so yeah tell me to check on the latest  :-)

quite a large modpack in case of inter-mod interraction all the polular mods are there. I recently added an old (?) mod playerAPI to make extrautilities deepdark portal work with galacticraft installed - they would be most likely other candidates

but running single player, same mods - I just removed the FE client mod and removing the nether portal works fine (break obsidian block and the portal is gone ...)

server says:
```
[22:19:11] [Server thread/WARN]: Failed to handle packet for /x.x.x.x:64152
net.minecraft.util.ReportedException: Exception while updating neighbours
	at net.minecraft.world.World.func_147460_e(World.java:730) ~[ahb.class:?]
	at net.minecraft.world.World.func_147459_d(World.java:650) ~[ahb.class:?]
	at net.minecraft.world.World.func_147444_c(World.java:613) ~[ahb.class:?]
	at net.minecraft.world.World.markAndNotifyBlock(World.java:488) ~[ahb.class:?]
	at net.minecraft.world.World.func_147465_d(World.java:466) ~[ahb.class:?]
	at net.minecraft.world.World.func_147468_f(World.java:573) ~[ahb.class:?]
	at net.minecraft.block.Block.removedByPlayer(Block.java:1341) ~[aji.class:?]
	at net.minecraft.block.Block.removedByPlayer(Block.java:1335) ~[aji.class:?]
	at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:247) ~[mx.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:296) ~[mx.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73082_a(ItemInWorldManager.java:217) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:498) ~[nh.class:?]
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53) ~[ji.class:?]
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8) ~[ji.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.block.BlockPortal.func_149695_a(SourceFile:158) ~[amp.class:?]
	at net.minecraft.world.World.func_147460_e(World.java:697) ~[ahb.class:?]
	... 20 more
[22:19:11] [Server thread/INFO]: _jaz000_ lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}

**Comment by olee** [comment] 2015-06-16 02:20
You are right - update FE.
This issue should have been fixed.
Report back, if the issue still is there after updating FE.

**Comment by jaz000** [comment] 2015-06-16 18:27
I am sorry to report with build 744 I have the same problem :(
slightly different modpack this time - less mods

probably unimportant but the error appears on the server console, but not in the logs

**Comment by rhwilr** [comment] 2015-06-23 20:39
I have this exact problem as well. It still exists in FE build 765.
If I remove FE it works fine, but with it portals don't light up.
Even the worldgeneration in the nether is all wrong if i teleport there. It only generated netherrack and ores but no caves.
Hope this gets resolved soon.

**Comment by olee** [comment] 2015-06-24 12:08
The stuff you described there has nothing to do with this issue though.
This problem does not affect Nether world generation in any way.
I will check this problem next.

**Comment by JonMaker050** [comment] 2015-06-27 20:13
I have the same problema in last build, 

 :(

**Comment by olee** [comment] 2015-06-30 10:11
Confirmed - will check this right now and see where it needs to be fixed.

**Comment by olee** [comment] 2015-06-30 10:32
Ok let me take that back (I was too stupid and derped building a proper portal frame :sweat:).
I can confirm that creating portals works without a problem in latest FE builds.
I even tried it on my own server with a very huge modpack and it worked.

@rhwilr I need a list of your mods and see if something is causing that problem.
Also please try starting a small server / client with only FE and place a portal - it should work without a problem.

**Comment by rhwilr** [comment] 2015-06-30 13:09
I'm using FTB Infinity 1.6.2 https://feedthebeast.atlassian.net/wiki/display/PML/Infinity+1.7+1.6.2
It is still not working for me with the latest build. If i only install FE it works.
FTB Infinity without FE works fine as well, so it seems to be a compatibility issue with one of the mods.

**Comment by JonMaker050** [comment] 2015-06-30 20:52
I am using 1.7.10 with last Build of FE

Galacticraft, Mekanism, Opercomputer, BuildCraft, Alien Vs depredator, bibliocraft, flans mod, NEI, SecurityCraft

**Comment by Blazedazer** [comment] 2015-07-04 14:41
RR3 + mystcraft +Galacticraft
build #777 Nether portals won't create
without FE it's working fine

**Comment by olee** [comment] 2015-07-06 00:03
So FE + Galacticraft might be causing this issue... need to check thins when I have some time.

**Comment by luacs1998** [comment] 2015-07-06 01:06
The only reason I can think of is a conflicting ASM patch. I will need the output of `/feinfo debug`.

**Comment by Blazedazer** [comment] 2015-07-06 05:05
will provide the info when i get back from work.
placing blocks infront of the portal causes client disconnect, and destroying the portal frame a soft crash of the server.

anything else, info wise, you would like / need to help ?

**Comment by Blazedazer** [comment] 2015-07-06 15:05
Modlist
http://pastebin.com/ZR6kDnqj

Log for placing blocks infront of portal
http://pastebin.com/WcA9Wuka

when you restart the server with a placed block infront of a portal the server crashes untill you remove the block ( server does not crash on block placing, simply does not start up anymore if it was shut down)
http://pastebin.com/QT1Ms0pT

destroying a block of the portal fram results in the exact same errors/disconnects

my enabled modules
    Modules {
        B:Backups=true
        B:Chat=true
        B:Commands=true
        B:Economy=true
        B:PlayerLogger=true
        B:Scripting=true
        B:WEIntegrationTools=true
        B:WorldBorder=true
        B:perftools=true
    }

and finally output of /feinfo debug

feinfo debug
[17:05:06] [Server thread/INFO]: Injected patches:
[17:05:06] [Server thread/INFO]: block.BlockPortal_01
[17:05:06] [Server thread/INFO]: player.MixinEntityPlayer_01
[17:05:06] [Server thread/INFO]: command.MixinCommandHandler_01

**Comment by olee** [comment] 2015-07-06 20:31
Disabled the FE portal mixin in https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/24b2f9c0d89b4fc66f55f5aee46f217620903f4b for now.
This will remove all related crashes, however it removes the portal rendering tweak (which was not very important anyway...).

Will fix this all if I have some time again...

**Comment by luacs1998** [comment] 2015-07-07 15:19
Should be fixed in the [fix/portal_mixin branch](https://github.com/ForgeEssentials/ForgeEssentialsMain/tree/fix/portal_mixin) - will test the fix for a while before merging into master.

**Comment by luacs1998** [comment] 2015-07-07 15:27
http://www.mediafire.com/download/whf9gxocr4xro9r/forgeessentials-1.7.10-1.4.0-beta8-fix_portal_mixin-server.jar

**Comment by Blazedazer** [comment] 2015-07-07 15:34
will put it on for tests in an hour or so, will report back.

thanks for the quick fix ( is the fix for the op issue also included in the linked jar ? )

**Comment by luacs1998** [comment] 2015-07-07 15:44
You can try...

**Comment by Blazedazer** [comment] 2015-07-07 16:09
and here is the console output of the crash

http://pastebin.com/1VwVS47T

**Comment by jaz000** [comment] 2015-07-08 10:17
I can confirm original report is fixed - tested with build 781 (from Jenkins not the version linked above)
so that's a big thumbs up and happy smile from me :)

**Comment by Blazedazer** [comment] 2015-07-08 13:08
aye build 782 no problems as well

**Comment by luacs1998** [comment] 2015-07-09 00:28
Yes, because olee disabled the portals patch in build 781. You can use that, but I'd like you guys to try my patched build so it can be sure that the issue is fixed. Thanks.

**Comment by Blazedazer** [comment] 2015-07-09 07:02
i did it still crashed
http://pastebin.com/1VwVS47T

**Comment by olee** [comment] 2015-07-10 21:47
If it still crashes, you probably did not really update to the latest build .... is the only thing I can imagine.
Please check again.
As the patch was completely removed, it should not crash there (or is it possible for patches to load without being in the json file @luacs1998?)

**Comment by luacs1998** [comment] 2015-07-11 01:49
No, but I posted a manual build that tried to do the portals mixin properly, remember?

**Comment by olee** [comment] 2015-07-11 06:28
Well you tried to fix problems which weren't problems.
The Mixin did not fail because I extended BlockPortal or did some other stuff uncommon for Mixin.
But instead it's the concept of the code itself that fails which is why your efforts were useless in that regard.

**Comment by luacs1998** [comment] 2015-07-27 14:10
Continue in #1649

**Closed by luacs1998** 2015-07-27 14:10 UTC
Labels: bug
