### ISSUE TITLE
Problem with AuthLogin

### ISSUE THREAD

**Issue by Walrusz** [ForgeEssentials/ForgeEssentialsMain#1293] opened 2015-02-14 17:03 UTC
Hello, I am trying to put together an offline server.
(with allowOfflineReg=true and forceEnable=true)

When joining the server, I can't do anything. I try to press T or ESC, ut just drops me back.
Video: https://www.youtube.com/watch?v=U5bdfiCuw3Y

Any ide what causes this?

**Comment by luacs1998** [comment] 2015-02-15 04:45
This is extremely odd. We should not be interrupting the client opening menus and whatnot.

I'll investigate.

**Comment by luacs1998** [comment] 2015-02-15 04:50
Try to set canMoveWithoutLogin to true. If it doesn't work, let me know.

**Comment by Walrusz** [comment] 2015-02-15 10:36
Doesn't help. I can move but I still can't open the chat or pause menu.

**Comment by Walrusz** [comment] 2015-02-15 10:37
I tried removing all the other mods except this but that doesn't help either.
By the way, I'm using Forge 10.13.2.1291

**Comment by Walrusz** [comment] 2015-02-16 16:08
I assume this is the newest beta5 version now. It didn't fix it.

**Comment by Walrusz** [comment] 2015-02-17 20:17
If no one else reported this before, then maybe something's wrong at my end? Should I try with another Forge version?

**Comment by skicek** [comment] 2015-03-01 20:53
i can comfirm this too MC 1.7.10 forge 10.13.2.1291

**Comment by pablo191f** [comment] 2015-03-09 16:40
This happens for me too. MC 1.7.10 + Forge 10.13.2.1291

**Comment by DPxKnightxZero** [comment] 2015-03-20 16:39
Yeah I can confirm this an issue with the auth login :( I was hoping to make sure they couldn't do anything without reserving a slot.

**Comment by Pyeroh** [comment] 2015-03-25 04:07
I can confirm this issue, same that skicek and pablo191f

**Comment by luacs1998** [comment] 2015-03-25 07:59
@olee can I rely on you to find a solution to this?

**Comment by olee** [comment] 2015-03-29 06:17
Sorry but I have no affiliation with auth module and don't really want to support it.
There are more important features I want to concentrate on.

**Comment by NonanteSeize** [comment] 2015-03-31 13:46
Hmm. Same issue here. Simple Forge server with just ForgeEssentials installed on an offline server.
Using:
B:allowOfflineReg=true
B:autoEnable=false
B:canMoveWithoutLogin=true
B:forceEnable=true (false disables it since server is offline.)

**Comment by luacs1998** [comment] 2015-03-31 14:10
I am really out of ideas. Nothing we do (should) impact the opening and closing of clientside UIs like the pause menu.

If someone else has a way to fix it, please do and I will gladly accept your PR.

**Comment by Gid32** [comment] 2015-04-09 14:02
luacs1998, can it be truth that your AuthEventHandler.java subscribed to events that aren't needed?
also, can you rebuild FE with additional info(e.g. event name) in login error msg in this file (i think this is main EventHandler in auth module)
ForgeEssentialsMain/src/main/java/com/forgeessentials/auth/AuthEventHandler.java
or explain me/give link to explanation how can i build it by myself?

**Comment by luacs1998** [comment] 2015-04-09 16:08
We'll see about that.

**Comment by Gid32** [comment] 2015-04-11 11:51
fixed in beta6 (for me)

**Comment by Walrusz** [comment] 2015-04-11 20:32
Sorry for the off-topic comment, but is there a way to change lines like "Registration required. Try /auth help" to another language?

**Comment by luacs1998** [comment] 2015-06-08 11:04
I am unable to recreate this on build 731 - closing. Reopen if it's still an issue.

**Closed by luacs1998** 2015-06-08 11:04 UTC
Labels: bug
