### ISSUE TITLE
/help kicking non-Op Players

### ISSUE THREAD

**Issue by tethlah** [ForgeEssentials/ForgeEssentialsMain#1628] opened 2015-07-15 23:33 UTC
When my players who are not ops do /help, it kicks them with the following error.
http://prntscr.com/7t6i6f

I checked and made sure that global allow was set for mc.help, but they still get kicked.

**Comment by DPxKnightxZero** [comment] 2015-07-18 15:30
This error is caused by a mod conflict and has nothing to do with forge essentials. They creator of inpure core needs to see this crash not the FE team. Tell the creator the error and that he needs to change the way the help command is written so it is parsed correctly. Also make sure you use the latest 1.7.10 forge if you want the best results.

**Comment by olee** [comment] 2015-07-19 04:08
It's just as @DPxKnightxZero said.
There is something fishy with the help message of that command.
However we can still try to filter out such stuff through FE so it does not crash.
Could you tell us where that `/INpureCore` command comes from?

**Comment by olee** [comment] 2015-07-23 09:51
@tethlah I would need to know where that command `/INpureCore` comes from...

**Comment by olee** [comment] 2015-07-23 13:57
Fixed in https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/2855daac32cbdd0c3ca755d79fc99c72eac259fe

**Closed by olee** 2015-07-23 13:57 UTC
Labels: bug, mod-compatibility
