### ISSUE TITLE
Server fail to start with latest build

### ISSUE THREAD

**Issue by FiveEYZ** [ForgeEssentials/ForgeEssentialsMain#1344] opened 2015-03-14 03:28 UTC
Server is FTB Infinity 1.2.1

As title says it fails, even with or without fastcraft
been using build #434 just fine here is a log of whats happening http://paste.ubuntu.com/10594562/
something that's new for me is that patching u see in the log

and here is the crash it generate http://paste.ubuntu.com/10594565/

**Comment by luacs1998** [comment] 2015-03-14 03:52
Dupe of #1319

**Closed by luacs1998** 2015-03-14 03:52 UTC

**Comment by FiveEYZ** [comment] 2015-03-14 04:26
Well that would defeat the purpose of having a public server, when i need to force ppl to change some mods to connect. 

Anyway i got it working with beta5 from CF, but i might go up the build ladder to see what where it fails me.
