### ISSUE TITLE
Can't start Server with latest build on jenkins

### ISSUE THREAD

**Issue by ultrasn0w** [ForgeEssentials/ForgeEssentialsMain#1502] opened 2015-05-17 12:27 UTC
Hey there,
Just tried to update FE to the latest build, however my server did not start and the log spits out this:
http://pastebin.com/cAxQLTRy
Full log:
http://pastebin.com/ZYdezLXd

I found out that rolling back to Build #579 works fine, seems like https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/f5b36cd00a44658a079b2a8fb534f4cf1f566e8b caused this.

Greetings
ultrasn0w

**Comment by luacs1998** [comment] 2015-05-17 12:37
Dupe of #1497, add -Dfastcraft.asm.permissve=true to launch args

**Closed by luacs1998** 2015-05-17 12:37 UTC
