### ISSUE TITLE
Suggestion: Clear dropped items on a regularly basis

### ISSUE THREAD

**Issue by Sunconure11** [ForgeEssentials/ForgeEssentialsMain#1248] opened 2015-01-15 23:27 UTC
Can we add one of the abilities from the ClearLagg plugin, which is clearing dropped items, as well as other entities if needed, on a regularly basis? If it is already in the mod, how do I use it?

**Comment by luacs1998** [comment] 2015-01-16 01:44
It isn't implemented per-se, but you can hack around by using timed commands from the scripting module to call /butcher.

**Comment by RlonRyan** [comment] 2015-01-18 22:59
Does the wontfix tag really apply here?

**Comment by luacs1998** [comment] 2015-03-08 05:56
Seems like this is a dupe of #1132 - but since I closed that, ya...

**Comment by olee** [comment] 2015-04-21 18:45
As already said, use a scheduled command.
FE may be powerful, but we can't do any small feature where there are other solutions for it.

**Closed by olee** 2015-04-21 18:45 UTC
Labels: request, wontfix
