### ISSUE TITLE
Saving Permissions every few seconds

### ISSUE THREAD

**Issue by groveham** [ForgeEssentials/ForgeEssentialsMain#1404] opened 2015-04-13 21:23 UTC
I'm not sure what's going on but the mod seems to want to save the permissions every few seconds. I've had a look around and there doesn't seem to be a config option for this (maybe one could be added?). But at the moment it's spamming my console and my logs.

Running:

Mod: forgeessentials-1.7.10-1.4.0-beta6-server.jar
Forge: server-1.7.10-1291.jar

13.04 17:20:53 [Server] INFO [16:20:53] [Server thread/INFO] [ForgeEssentials]: Saving permissions...
13.04 17:20:49 [Server] INFO [16:20:49] [Server thread/INFO] [ForgeEssentials]: Saving permissions...
13.04 17:20:46 [Server] INFO [16:20:46] [Server thread/INFO] [ForgeEssentials]: Saving permissions...
13.04 17:20:45 [Server] INFO [16:20:45] [Server thread/INFO] [ForgeEssentials]: Saving permissions...
13.04 17:20:41 [Server] INFO [16:20:41] [Server thread/INFO] [ForgeEssentials]: Saving permissions...
13.04 17:20:36 [Server] INFO [16:20:36] [Server thread/INFO] [ForgeEssentials]: Saving permissions...

**Comment by olee** [comment] 2015-04-14 04:44
Duplicate of #1352

Permissions are only saved, if they have been changed (actually one second after no more changes happended).
If they are regulary saved, this means there's a mod or something else regulary changing / registering permissions in one or the other way.
Please try to find out which mod / action results in the permissions being saved and report it in the other thread.

**Closed by olee** 2015-04-14 04:44 UTC
