### ISSUE TITLE
Permissions spam-saved every 3 seconds

### ISSUE THREAD

**Issue by Paul17041993** [ForgeEssentials/ForgeEssentialsMain#1491] opened 2015-05-12 09:11 UTC
Permissions are saved every 3 seconds, which is not only excessive but spams the console output and the logs. The permissions files should only be saved after being modified by the server and with world saves/backups.

![fe perm spam](https://cloud.githubusercontent.com/assets/3912867/7583655/b260cb76-f8da-11e4-8c3c-ec00f4867f4a.png)

**Comment by evernife** [comment] 2015-05-12 09:46
Dupe of: #1403

**Closed** 2015-05-12 10:02 UTC
