### ISSUE TITLE
/trade doesn't work properly

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentialsMain#1565] opened 2015-06-06 14:54 UTC
When trading, the seller has the item removed from his inventory, but it's not given to the buyer.

**Comment by olee** [comment] 2015-06-08 23:17
Only happens with some players though.
Needs more investigation and should really be fixed asap.

**Comment by olee** [comment] 2015-06-21 15:04
Is there anyone able to reproduce that issue?
Even with a lot of testing I was not able to reproduce this.
If this is not reproducible any more, I'd say we close this.

**Comment by luacs1998** [comment] 2015-06-22 02:45
Is this fixed as of 0194e10c4c433126c4e5710ab2b1f0b9fc8a7d9d ?

**Comment by olee** [comment] 2015-06-23 04:18
That change did not affect the exchange of items at all.
There was a problem with the chat messages sent.
However I was not able to reproduce this any more so it might have been fixed some other time.

**Comment by luacs1998** [comment] 2015-06-26 13:43
In that case is this still an issue?

**Comment by olee** [comment] 2015-06-30 11:17
(Accidentiall closed)

I found some new interesting information about this bug!
When I traded some items with a player on my server (trading items from him to me worked before), the items ended up being dropped **at his bed** instead of at the player location! Also `/tpa` requests to this player would end up players being teleported to his bed instead of to the player as well!

**Comment by olee** [comment] 2015-07-01 12:42
Continued in #1612

**Closed by olee** 2015-07-01 12:42 UTC
Labels: bug, high-priority, in-progress
