### ISSUE TITLE
[1.8] WorldEdit duplicate

### ISSUE THREAD

**Issue by kreezxil** [ForgeEssentials/ForgeEssentialsMain#1644] opened 2015-07-23 17:24 UTC
Issue: FE 1.8 Snapshot 8 is downloading or installing duplicate world-edit mods and then the dedicated server halts because of that

crash report:
https://gist.github.com/d83444b85f1dba2e146b

fml server latest:
https://gist.github.com/3c89916376004ad53f76

**Comment by olee** [comment] 2015-07-23 17:40
Delete the dev jar of worldedit.
I don't know how it ended up there...
I never tried actually running the built FE 1.8 mod outside of dev environment (which is why it's called experimental build).

**Comment by olee** [comment] 2015-07-23 18:09
Confirmed - it extracts the correct -dist jar, but also the dev jar.
The build.gradle needs some fixing...

**Comment by olee** [comment] 2015-07-23 18:45
Fixed in https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/4865029b6f38f51ef9cabbf64545b7dce9bcdaa2

**Closed by olee** 2015-07-23 18:45 UTC
Labels: accepted, bug

**Comment by liach** [comment] 2015-07-23 23:47
Can we remove sk89q's maven as it's always throwing time out?

**Comment by luacs1998** [comment] 2015-07-24 01:27
No, because we get worldedit (for 1.7) from there.

I'll speak to SK about timeouts, might be a problem with his artifactory instance.

**Comment by olee** [comment] 2015-07-24 03:22
Actually @sk89q's maven was removed and now WE files are placed as copies into the lib directory, because the 1.8 builds are not on the maven yet.
