### ISSUE TITLE
Problems with authentication

### ISSUE THREAD

**Issue by HaoSs07** [ForgeEssentials/ForgeEssentialsMain#1269] opened 2015-01-28 16:21 UTC
~~~tested in beta 3 and 4. do i need to do anything special to get worldedit to work ?
any of the normal //something that worldedit have does not work . ~~~ luacs edit: duplicate of #1266

p.s. also authentication seems to be broken in latest beta. When you want to type something, the chat disappears and you re spammed with the authme help notification . same for escape menu.

**Comment by barthy** [comment] 2015-01-28 18:52
on my part i can change blocks etc with world edit   it is just when it comes to link world edit with commands from FE that doesnt seems to work as such as making Areas

**Comment by olee** [comment] 2015-03-14 11:20
Duplicate of https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1293

**Closed by olee** 2015-03-14 11:20 UTC
Labels: bug
