### ISSUE TITLE
Permissions Not Saving - Tried with new forge release 460

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentialsMain#1362] opened 2015-03-23 00:43 UTC
After being told to update I cannot save permissions anytime the server shuts down and boots up all my permissions are gone.

**Comment by luacs1998** [comment] 2015-03-23 02:25
Logs?

**Comment by DPxKnightxZero** [comment] 2015-03-23 12:25
Okay here https://drive.google.com/file/d/0B1fY2sKXiHd7bmJPYk9TZnRuMUE/view?usp=sharing

**Comment by DPxKnightxZero** [comment] 2015-03-23 12:32
The log was too big to post I sent you the full log because I never crashed :(

**Comment by luacs1998** [comment] 2015-03-23 14:03
Seems like a dupe of #1354

**Closed by luacs1998** 2015-03-23 14:03 UTC

**Comment by DPxKnightxZero** [comment] 2015-03-23 14:09
What does that mean?

**Comment by olee** [comment] 2015-03-23 14:12
This issue and #1354 are the same - it's a duplicate.

**Comment by DPxKnightxZero** [comment] 2015-03-23 15:03
How is it the same?!!! Mine is not saving permission NO CRASH and his is CRASHING?~.~
