### ISSUE TITLE
Skipping ticks when saving permissions

### ISSUE THREAD

**Issue by kerts93** [ForgeEssentials/ForgeEssentialsMain#1403] opened 2015-04-13 20:28 UTC
As soon as I add FE, server starts skipping ticks, I think it has something to do with Permissions, because it skips ticks as soon as it says Saving Permissions...
![Server console](http://i.imgur.com/PfRtfMc.png)

Same thing occurs if Permissions run using flatfile or sql (sql of course has a lot more skipping ticks).
As soon as I remove FE, everyting is back okay, yes there are few tick skips but quite rare.

Used version 1.4.0 beta 6 from curseforge. Our server is now running on SSD so that shouldn't also be an issue. Also I noticed that it cannot connect to database if I set host as localhost?

(I don't know what versions in between did, since I had FE disabled, now tried it again for next update)

**Comment by luacs1998** [comment] 2015-04-14 01:57
Try assigning more memory, or get better hardware if possible. If not, consider removing some mods.

This issue is caused by the CPU not being able to keep up with the processing that needs to be done. FE's perms saving can cause quite a bit of overhead, this coupled with other resource intensive mods can cause the server to slow down.

We should be able to optimize as much as we can, but beyond that, it's entirely up to you.

**Comment by kerts93** [comment] 2015-04-14 03:47
I'm sorry, but if 10GB of DDR3 RAM (server itself has 32gb) and 8 cores of 3.80GHz is not enough then what is?

Our server's CPU is not even 100% used.

**Comment by helinus** [comment] 2015-04-14 08:57
Minecraft is mostly singlethreaded so multiple cores doesn't matter as much as the singlethread perfomance of the processor.
CPU usage is usually measured with all cores combined so a single core can still be overloaded while overall usage is below 100%.

**Comment by olee** [comment] 2015-04-14 09:18
Did you trigger the permission saving yourself with `/p save` / by changing some permissions?

Also please test the same server without FE and check if you get **no** skips at all, as well as check the CPU load.
It might be that your server is already at it's limit with all the mods you use and that little bit of performance FE needs is too much for the server.

I will also keep this issue open as a reminder to improve saving / loading of permissions so it runs in a separate thread.

**Comment by TimB1087** [comment] 2015-04-14 12:35
I can chime in and say that the OP's SS looks all too familiar. This has been occurring on my server as well. Although it is a modpack, I can say that A) we built our modpack to be as server and resource friendly as possible and B) at 7GB allotted+custom arguments and dedicating a CPU core to the process, we still experience TPS issues, even when all DIMs read a full 20 tps. Console never shows RAM usage above 40%, however.

I should also mention that this has been happening for quite some time, and just ignored it, thinking maybe the worst it was doing was filling up our console logs. However, seeing this issue reported as taking a hit to tps, I begin to wonder if that's one of the causes of our server's low tps issues. (We typically troubleshoot the cause of them, but sometimes scratch my head while looking at opis, wondering where the lag is coming from.)

I can provide more details about our server later tonight when I'm home, but I just wanted to point out that the OP isn't alone.

Oh, and this happens after reboots, etc. Yes, I have customized permissions. I do so only using in game commands. However, I don't think I've ever ran a /p save or reload command. I just set the permission and, because it works instantly, I never think to save or reload. Could that be part of the issue? Could this also be related to the issue regarding permissions sometimes being reset to defaults after a server crash?

**Comment by olee** [comment] 2015-04-16 04:53
Thanks for the detailed feedback!
(If we could just always get detailed issue posts like that and not "This does not work. PERIOD")

First: Because #1352 and this issue are overlapping, I'm going to merge #1352 into this one because we have some more detailed feedback in here. I'm going to add all relevant information of #1352 here first:

@FiveEYZ
>FE is "Saving permissions..." for each sapling placed by a Forestry farm, i was alone on the server and watched the farm and with /p debug

@BobertTheThird
>This also happens with with ComputerCraft's Melee Turtles whenever they attack (which when setup as a mob farm is quite often)

So the permission saving is definitely eating up way more performance than I originally guessed. Normally, this would not be a great problems as permissions should not change frequently - maybe just a few times each day (except when setting up server configuration). FE uses an event that gets triggered when a permission is changed and marks the whole permission storage as *dirty*. As soon as the permission storage is marked dirty and there have been no more changes to permissions in the last second, FE will save the permissions to disk.

The problem now is that for some reason, this dirty flag is either not being cleared (maybe an exception while saving permissions, before the flag could be unset?) or for some reason it is set again and again by some other code.

I think that both could be true in some cases.
By looking at http://prntscr.com/6trynw it seems to save constantly which would happen if the dirty-flag does not get reset because of some exception, however no exception has been reported...
@TimB1087: Could you reproduce the above log take a look not only at console, but at the log file as well? It can often contain information that is not in the console. **After** testing this, you can update to latest build (489) and see, if the problem still exists?

@FiveEYZ
@BobertTheThird
As for the cases where permissions are saved when doing certain actions, this could have various reasons. ~~One possible reasons I could imagine are fake players, which are used by these mods to do certain actions.~~ Screw that - just while I was writing this and checking the code, I noticed that actually every time a fake player does something which is controlled by a permission, the system would recognize the fake player and add it to the special _FAKEPLAYERS_ group .... **each time**.
I fixed this in build 489 so please test this as well.

I think with that build, this issue and #1352 should be fixed.

**Comment by Biofusionz** [comment] 2015-04-16 09:08
I am still getting the Saving Permissions text in console. It does seem less frequent now, at once a minute instead of once every few seconds
[11:03:00] [Server thread/INFO] [ForgeEssentials]: Saving permissions...
[11:04:00] [Server thread/INFO] [ForgeEssentials]: Saving permissions...
[11:05:00] [Server thread/INFO] [ForgeEssentials]: Saving permissions...
[11:06:00] [Server thread/INFO] [ForgeEssentials]: Saving permissions...
[11:07:00] [Server thread/INFO] [ForgeEssentials]: Saving permissions...

**Comment by olee** [comment] 2015-04-16 11:16
Ok so it is still setting the dirty-flag for some reason.
Can you pastebin me a list of the mods you used?
Also do these frequent saves happen directly after server start?

**Comment by Biofusionz** [comment] 2015-04-16 11:37
Here's the modlist: http://paste.silvaniastudios.com/paste/view/ec722239

And yes, it happens directly after a server restart

**Comment by TimB1087** [comment] 2015-04-16 21:10
Our server was rebooted at 4pm EST. Here are some logs that were generated after that reboot:
This is still with the version of FE I was using previously (in the process of updating it now to test).

FML's "latest.log": http://pastebin.com/x0sZm29v
FML's "fml-junk-earlystartup.log": http://pastebin.com/pAn6TUc2

I'll go ahead and update, and report back my findings and new logs.

**Comment by olee** [comment] 2015-04-16 23:47
@TimB1087 
Well this just shows that the server seems to be overloaded by some mod and not FE.
The "saving permissions" is not there any more and still the server needs to skip a lot of ticks.
I'd probably say that you will get the same result if you run the same modpack without FE (on the same server). FE has nearly no tick handlers at all so it does not really affect server performance except the protection module. 

As the original issue with the frequent permission saves is solved, I'm closing this issue for now. If you still have any questions in regards to your tick-skipping problem, ask them in IRC (or here if you can't use IRC).

**Comment by olee** [comment] 2015-05-11 21:06
After setting up my own server and fixing a problem where permissions would not save at all except on server shutdown (https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/0806dc4e2864fb0ece5ffcae85cc66dd59be670c), permissions keep saving every minute again for some reason.

Now that I am able to reproduce this issue, I can try out some fixes for this on my own server.

**Comment by evernife** [comment] 2015-05-11 23:12
Same here, I update to the last version of Forge and FE, get this erros.

**Comment by evernife** [comment] 2015-05-12 09:49
I downgraded my FE and the error stops. Think it is connected to the newest commits.
I am using the Build-Number: 531

**Comment by olee** [comment] 2015-05-12 15:46
Now it is finally really fixed.

@evernife actually the new version fixed another bug which just made these messages visible again.
So you should not have downgraded.

**Closed** 2015-05-12 15:45 UTC
Labels: bug

**Comment by evernife** [comment] 2015-05-12 16:33
:c

Okay, i will upgrade again now that the fix was made :D

**Comment by Flexico** [comment] 2015-05-16 11:22
Same thing happens to me when I have a Buildcraft Quarry running. The Filler and Builder don't seem to have that effect though. Forge 1388 and FE 1.4.0-beta6-server.

**Comment by olee** [comment] 2015-05-17 13:56
What do you expect, if you don't test it with the **latest** build where this bug has been fixed :sweat:

**Comment by Flexico** [comment] 2015-05-17 17:13
Wait, that's not the latest build? I downloaded it like 2 days ago ... *checks* Ok, I downloaded it from CurseForge, but that one was last updated on April 8. Where is the latest build?

**Comment by evernife** [comment] 2015-05-17 17:36
http://ci.forgeessentials.com/job/ForgeEssentials/

**Comment by Flexico** [comment] 2015-05-17 17:53
Thank you~
