### ISSUE TITLE
Fastcraft + ForgeEssentials

### ISSUE THREAD

**Issue by SakuraTheBabyfur** [ForgeEssentials/ForgeEssentialsMain#1410] opened 2015-04-17 00:17 UTC
I seem to be having a problem with fastcraft alongside forge essentials, whenever I start the server this shows up 

http://pastebin.com/YgvACmSV

I would like to point out I have forge build 490 of essentials installed, as well as the newest version of fastcraft, 1.21

I have already tried to edit the java arguments, here is the .bat i use to start my server

title run-minecraft
java -server -d64 -Xms2048M -Xmx4056M -Dfastcraft.asm.permissive -jar minecraft_server.jar
pause

I already asked the creator of fastcraft if it was an issue with fastcraft, and he said "It's crashing due to class loading issues caused by ForgeEssentials."

**Comment by Greatone123** [comment] 2015-04-17 00:51
I think they've already discussed it over here:

https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1372

**Comment by luacs1998** [comment] 2015-04-17 02:23
Yep, as mentioned, dupe of #1372. Was working with Player on this a while ago, but it seems a FML PR is needed to fix this.

**Closed by luacs1998** 2015-04-17 02:23 UTC
