### ISSUE TITLE
[Bug] Unable to click links in chat

### ISSUE THREAD

**Issue by Biofusionz** [ForgeEssentials/ForgeEssentialsMain#1342] opened 2015-03-13 13:43 UTC
Can't click any type of link in chat, even if sent from irc.

**Comment by olee** [comment] 2015-03-13 15:23
That's not a bug, it's a feature...
The problem is that for links to be clickable, we would have to scan the messages for links and specifically extract them.
MC might have an integrated feature for that tough...

**Comment by luacs1998** [comment] 2015-03-13 17:29
Yes, MC has it built in. I seem to remember their was a forge bug or something regarding this, but will need to check.

**Comment by Biofusionz** [comment] 2015-04-05 19:54
I know you guys have been working hard doing other stuff, but is there any progress on this? It's kind of a hassle having to type links in every time one is sent on the server.

**Comment by olee** [comment] 2015-04-06 01:36
The problem is that the recognition of links has a few problems with color-codes.
We will try to fix this soon.

**Comment by luacs1998** [comment] 2015-04-23 02:40
Can someone try this with the latest Forge?

**Comment by olee** [comment] 2015-04-23 04:48
It still does not work. I will take care of it soon.
(Somehow I forgot to assign this to me).

**Comment by olee** [comment] 2015-05-24 22:18
Will be fixed once https://github.com/ForgeEssentials/ForgeEssentialsMain/tree/feature/chat gets merged.

**Comment by olee** [comment] 2015-05-25 09:16
Closed by #1532 which will be merged soon

**Closed by olee** 2015-05-25 09:16 UTC
Labels: bug
