### ISSUE TITLE
Error and client crash when moving in a server with FE (lastest version + forge 10.13.2.1291)

### ISSUE THREAD

**Issue by Fraste01** [ForgeEssentials/ForgeEssentialsMain#1282] opened 2015-02-07 16:05 UTC
As the title I crash when I join a server created by me on my computer with Forge Essentials and I get this error:
[16:44:24] [Server thread/ERROR] [FML/]: Exception caught during firing event com.forgeessentials.util.events.PlayerMoveEvent@1f7b093:
java.lang.NullPointerException
	at com.forgeessentials.worldborder.ModuleWorldBorder.playerMove(ModuleWorldBorder.java:163) ~[ModuleWorldBorder.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_95_ModuleWorldBorder_playerMove_PlayerMoveEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at com.forgeessentials.util.events.ForgeEssentialsEventFactory.playerTickEvent(ForgeEssentialsEventFactory.java:32) [ForgeEssentialsEventFactory.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_140_ForgeEssentialsEventFactory_playerTickEvent_PlayerTickEvent.invoke(.dynamic) [?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:350) [FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:353) [yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) [mw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) [nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) [jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8) [jd.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[16:44:24] [Server thread/ERROR] [FML/]: Index: 1 Listeners:
[16:44:24] [Server thread/ERROR] [FML/]: 0: NORMAL
[16:44:24] [Server thread/ERROR] [FML/]: 1: ASM: com.forgeessentials.worldborder.ModuleWorldBorder@d55c59 playerMove(Lcom/forgeessentials/util/events/PlayerMoveEvent;)V
[16:44:24] [Server thread/ERROR] [FML/]: 2: ASM: com.forgeessentials.teleport.portal.PortalManager@16170f7 playerMove(Lcom/forgeessentials/util/events/PlayerMoveEvent;)V
[16:44:24] [Server thread/ERROR] [FML/]: 3: ASM: com.forgeessentials.permissions.core.PermissionEventHandler@190f27 playerMoveEvent(Lcom/forgeessentials/util/events/PlayerMoveEvent;)V
[16:44:24] [Server thread/ERROR] [FML/]: 4: ASM: am2.ShrinkHandler@1df8c00 onEntityLiving(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
[16:44:24] [Server thread/ERROR] [FML/]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$PlayerTickEvent@159a0f0:
java.lang.NullPointerException
	at com.forgeessentials.worldborder.ModuleWorldBorder.playerMove(ModuleWorldBorder.java:163) ~[ModuleWorldBorder.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_95_ModuleWorldBorder_playerMove_PlayerMoveEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at com.forgeessentials.util.events.ForgeEssentialsEventFactory.playerTickEvent(ForgeEssentialsEventFactory.java:32) ~[ForgeEssentialsEventFactory.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_140_ForgeEssentialsEventFactory_playerTickEvent_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:350) [FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:353) [yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) [mw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) [nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) [jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8) [jd.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[16:44:24] [Server thread/ERROR] [FML/]: Index: 3 Listeners:
[16:44:24] [Server thread/ERROR] [FML/]: 0: NORMAL
[16:44:24] [Server thread/ERROR] [FML/]: 1: ASM: com.forgeessentials.commands.util.CommandsEventHandler@1dbfe2a tickStart(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[16:44:24] [Server thread/ERROR] [FML/]: 2: ASM: hardcorequesting.EventHandler@2102c4 onEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[16:44:24] [Server thread/ERROR] [FML/]: 3: ASM: com.forgeessentials.util.events.ForgeEssentialsEventFactory@189bb1d playerTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[16:44:24] [Server thread/ERROR] [FML/]: 4: ASM: com.sk89q.worldedit.forge.ThreadSafeCache@9f7aa7 tickStart(Lcpw/mods/fml/common/gameevent/TickEvent;)V

Thank's for help.

**Comment by luacs1998** [comment] 2015-02-08 01:54
Duplicate of #1256, read workaround posted in that issue topic.

I will fix this once and for all when I have time.This is seriously annoying -.-

**Closed by luacs1998** 2015-02-08 01:54 UTC
