### ISSUE TITLE
Item Use Protection not working

### ISSUE THREAD

**Issue by killerpommes** [ForgeEssentials/ForgeEssentialsMain#1685] opened 2015-08-07 09:01 UTC
Hi,
i tried to deny the use of the dolly from the Mod Jabba.
But it seems not working. I tried differend commands like:
````
/p user <name> false fe.protection.use.JABBA.mover
/p user <name> deny fe.protection.use.JABBA.mover
````
Maybe i did not do it right. 
Please Help

I use build forgeessentials-1.7.10-1.4.2.857-server on Forge 1.7.10-1448

**Comment by olee** [comment] 2015-08-07 13:34
Did you try `/protectdebug` or `/p debug`?

**Comment by killerpommes** [comment] 2015-08-07 14:45
i see the message 
````
§bfe.protection.use.JABBA.mover§f = §4false
§f  zone [§5_SERVER_§f] user [§5<PROFILE NAME>§f]
````

**Comment by olee** [comment] 2015-08-07 21:15
Nothing else? Just that one permission check?
As it shows there the permission was correctly denied.
If it still works, that might mean JABBA is another of those stupid mods ignoring proper event handling...
Will need some investigation.

**Comment by killerpommes** [comment] 2015-08-07 21:26
the full message is 

````
§bfe.pl.wand§f = §4false
§f  zone [§5_ROOT_§f] group [§5_ALL_§f]
§bfe.protection.interact.minecraft.chest§f = §2true
§f  zone [§5_PLOT_6§f] group [§5PLOT_OWNER§f]
§bfe.protection.use.JABBA.mover§f = §4false
§f  zone [§5_SERVER_§f] user [§5<name>§f]
§bfe.pl.wand§f = §4false
§f  zone [§5_ROOT_§f] group [§5_ALL_§f]
§bfe.protection.interact.minecraft.planks.1§f = §2true
§f  zone [§5_PLOT_6§f] group [§5PLOT_OWNER§f]
§bfe.protection.use.JABBA.mover§f = §4false
§f  zone [§5_SERVER_§f] user [§5<name>§f]
§bfe.pl.wand§f = §4false
§f  zone [§5_ROOT_§f] group [§5_ALL_§f]
[CHAT] §bfe.protection.use.JABBA.mover§f = §4false
CHAT] §f  zone [§5_SERVER_§f] user [§5<name>§f]
````

If i can help, just say something :)

**Comment by AnrDaemon** [comment] 2015-08-07 23:21
It checks for  perms to interact with target object, then to use dolly.
however, the "use" happens despite apparent denial.
![JABBA=/=FE interaction. (312873b)](http://project.rootdir.org/gallery/minecraft-1.7.10/?view=javaw-20150808-012301.26.jpg)

**Comment by olee** [comment] 2015-08-07 23:47
Ok I checked the source code and it seems the dolly uses this Item method to trigger the activation:
````
public boolean onItemUseFirst(ItemStack stack, EntityPlayer player, World world, int x, int y, int z, int side, float hitX, float hitY, float hitZ) { ... }
````
However forge has a problem with this event - here is the relevant forge code:
````
        PlayerInteractEvent event = ForgeEventFactory.onPlayerInteract(p_73078_1_, Action.RIGHT_CLICK_BLOCK, p_73078_4_, p_73078_5_, p_73078_6_, p_73078_7_, p_73078_2_);
        if (event.isCanceled())
        {
            thisPlayerMP.playerNetServerHandler.sendPacket(new S23PacketBlockChange(p_73078_4_, p_73078_5_, p_73078_6_, theWorld));
            return false;
        }

        if (p_73078_3_ != null && p_73078_3_.getItem().onItemUseFirst(p_73078_3_, p_73078_1_, p_73078_2_, p_73078_4_, p_73078_5_, p_73078_6_, p_73078_7_, p_73078_8_, p_73078_9_, p_73078_10_))
        {
            if (p_73078_3_.stackSize <= 0) ForgeEventFactory.onPlayerDestroyItem(thisPlayerMP, p_73078_3_);
            return true;
        }
````
As you can see, even if `event.useBlock` and `event.useItem` are set to `false`, it will still run the dolly code. Actually forge should use this line instead:
````
        if (event.useItem != Event.Result.DENY && p_73078_3_ != null && p_73078_3_.getItem().onItemUseFirst(p_73078_3_, p_73078_1_, p_73078_2_, p_73078_4_, p_73078_5_, p_73078_6_, p_73078_7_, p_73078_8_, p_73078_9_, p_73078_10_))
        {
            if (p_73078_3_.stackSize <= 0) ForgeEventFactory.onPlayerDestroyItem(thisPlayerMP, p_73078_3_);
            return true;
        }
````

I suggest making a PR to forge. It is really surprising this was not noticed yet...

**Comment by luacs1998** [comment] 2015-08-08 01:13
Shall we mix this in?

**Comment by AnrDaemon** [comment] 2015-08-08 01:16
That's  arguable "needshook". The FE part is right, and works as intended, if I'm reading what I see.
The problem is upstream behavior that is just wrong.

**Comment by olee** [comment] 2015-08-08 01:25
Yeah I just marked it as needshook as a reminder that it needs a modification of MC code.

**Comment by luacs1998** [comment] 2015-08-09 16:45
Can you try with this build and see if the issue is fixed?

http://www.mediafire.com/download/qc2a3lzd95dp2hc/forgeessentials-1.7.10-1.4.2.0-server-fix1685.jar

**Comment by AnrDaemon** [comment] 2015-08-09 16:52
For me it appears to be working. I now get chest UI instead of picking the chest.

**Comment by killerpommes** [comment] 2015-08-09 17:59
Same here. I wanted to test this with plots from different people.
Thats because i did not answered yet.
I had no chance to do it yet.

**Closed** 2015-08-13 16:21 UTC
Labels: bug, needshook
