### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by zlepper** [ForgeEssentials/ForgeEssentialsMain#1319] opened 2015-03-03 13:49 UTC
http://paste.ubuntu.com/10515235/
I get that crash whenever I attempt to start my server. Removing FE prevents the crash from happening.

**Comment by olee** [comment] 2015-03-03 13:52
`Caused by: java.lang.ClassNotFoundException: powercrystals.minefactoryreloaded.modhelpers.thaumcraft.Thaumcraft`

I don't think there's any more to say then that.
It's probably just bad luck, that without FE it does not try to load some function of Thaumcraft or MFR.
At least it's 100% not FE's fault as there is a missing Thaumcraft class.

**Comment by skyboy** [comment] 2015-03-03 17:01
Oh, you're causing this.

If you read further: `Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.block.Block`

The actual error is probably something in the ASM data for Block when it got transformed by both of our transformers, but that error is swallowed by the version of LaunchWrapper used for 1.7.10.

**Comment by luacs1998** [comment] 2015-03-03 23:01
For the record, we're using transformers from the SpongePowered/Mixin project, so you may want to speak with them.

**Comment by skyboy** [comment] 2015-03-03 23:46
I'm still not sure that it's FE in particular, this is just the first time someone can reliably cause and  fix the break. There's an attempted fix going out on my side that may resolve entirely or move the crash to another location. FE may just be altering the load order in such a way it triggers this.

**Comment by olee** [comment] 2015-03-03 23:55
Keeping it open until we know a solution for this problem. ok?

**Comment by zlepper** [comment] 2015-03-04 19:07
The latest version of the CoFH mods seems to have fixed the issue. So you can close this if you feel it done.

**Comment by skyboy** [comment] 2015-03-05 17:49
Yay, load orders. I hate these bugs.

**Comment by notyourshield** [comment] 2015-03-07 18:42
Seems like it's back with the latest CoFH Core.

**Comment by olee** [comment] 2015-03-14 11:09
According to @zlepper the issue seems to be fixed so I'm closing this for now.

**Closed by olee** 2015-03-14 11:09 UTC
Labels: bug, modcompat
